### ISSUE TITLE
(Question) tag FIREFOX_90_0_RELEASE does not exist (?)

### ISSUE THREAD

**Issue by wannaskoo** [Divested-Mobile/Mull-Fenix#10]
I tried building Mull 90.1.1 and got "Hg checkout of 'FIREFOX_90_0_RELEASE' failed" , so i checked on mozilla-release and indeed the tag is not there (FIREFOX_89_0_RELEASE exists, for instance), so what tag did you use when building Mull for your repo?

**Comment by SkewedZeppelin** [comment]
I compiled 90.1.1 against tip, until RELEASE is tagged.

**Comment by wannaskoo** [comment]
Thanks for replying, today i learned another thing.

**Comment by SkewedZeppelin** [comment]
And the tags:
https://hg.mozilla.org/releases/mozilla-release/tags
