### ISSUE TITLE
Add a themed icon

### ISSUE THREAD

**Issue by Darkempire78** [Divested-Mobile/Mull-Fenix#100]
Please add a themed icon to match with Android 13 systems

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by SkewedZeppelin** [comment]
It is on my TODO list, I already did my other apps.

**Comment by mikitakahazekura** [comment]
Fennec has themed monochrome icons for android 13
https://gitlab.com/relan/fennecbuild/-/merge_requests/22

**Comment by ChinoGoblino** [comment]
On the GitlLab page it says you couldn't work out the transparency. Is this icon what you were looking for?

![raccoon-monochrome](https://github.com/Divested-Mobile/Mull-Fenix/assets/71302825/3e3cc6ac-d4a2-4886-9d96-2c710438c161)

**Comment by SkewedZeppelin** [comment]
@ChinoGoblino 
thank you! I've pulled it in for next update

**Comment by SkewedZeppelin** [comment]
Mull 117.1.0-2 is up with @ChinoGoblino's monochrome icon
