### ISSUE TITLE
All installed add-ons are displayed in English. The operating system and browser are Russified. Also, the description of additions is also in Russian.

### ISSUE THREAD

**Issue by Someone-G** [Divested-Mobile/Mull-Fenix#102]
All installed add-ons are displayed in English. Although I know that they are 100% Russified, i.e. they must contain the Russian language. The operating system and browser are Russified. Also, the description of additions is also in Russian.
![Screenshot_20221122-142712](https://user-images.githubusercontent.com/108881628/203303845-65e0293c-a98f-4fcf-bb33-2c507a42b96d.png)
![Screenshot_20221122-142717](https://user-images.githubusercontent.com/108881628/203303862-47f85229-f5f2-4ec2-bc7b-a049651dfd7b.png)
![Screenshot_20221122-142734](https://user-images.githubusercontent.com/108881628/203303878-963dbad4-b76d-46c4-a0a1-460be31ba6e2.png)
![Screenshot_20221122-142810](https://user-images.githubusercontent.com/108881628/203303892-83196848-5b2d-4fb2-a98d-2d33c1fc13c5.png)
![Screenshot_20221122-142744](https://user-images.githubusercontent.com/108881628/203303906-f31b83c2-79a2-4033-8cff-a14e311ac1e6.png)

**Comment by Someone-G** [comment]
I checked 5 add-ons that are guaranteed to contain Russian localization and all of them are displayed in English.

**Comment by SkewedZeppelin** [comment]
This is likely expected due to the language overrides:
- https://github.com/Divested-Mobile/Mull-Fenix/blob/master/preferences/userjs-arkenfox.js#L126
- https://github.com/Divested-Mobile/Mull-Fenix/blob/master/preferences/userjs-arkenfox.js#L131
- https://github.com/Divested-Mobile/Mull-Fenix/blob/master/preferences/userjs-arkenfox.js#L821

**Comment by spvkgn** [comment]
https://gitlab.com/relan/fennecbuild/-/issues/22#note_1071465043

**Comment by SkewedZeppelin** [comment]
This is fixed in Mull v113.0.0 thanks to @paidforby !
