### ISSUE TITLE
How do I get v107.1.0 or the latest version?

### ISSUE THREAD

**Issue by stantios** [Divested-Mobile/Mull-Fenix#103]
I tried getting the latest version of F-droid but it seemed that the latest version was v105.1.0 and I saw on Github releases that the latest is v107.1.0?

**Comment by SkewedZeppelin** [comment]
Add my repo for it: https://divestos.org/index.php?page=our_apps#repos

**Comment by CreeperFace00** [comment]
You'll also need to turn on "Include incompatible versions" in F-Droid's settings, as well as uninstall the old version because of the mismatched signatures. This will clear all of the appdata, so watch out for that.
