### ISSUE TITLE
Adding OLED dark theme to Mull as a patch

### ISSUE THREAD

**Issue by ArtikusHG** [Divested-Mobile/Mull-Fenix#105]
Hello, as you know, firefox doesn't currently have an OLED dark theme, even though this is a feature *a lot* of users really want. [There is a PR](https://github.com/mozilla-mobile/fenix/pull/27789) for this which is mostly functional, but the approval process from the mozilla team is very long, and it's most likely not getting merged anytime soon. Thus, I propose to add this patch into Mull. If you approve, I will open a PR to merge this in .patch format, I am creating this issue just to know your take on this and have some discussion.

I understand UI changes are mostly beyond the scope of the project, however I feel like a little optional enhancement like this would be really great for those users who need this feature.

**Comment by SkewedZeppelin** [comment]
I'll pull it in next update, but I won't hesitate to drop it once it doesn't apply cleanly.

**Comment by ArtikusHG** [comment]
Great! If you want, I can make a PR myself. Thank you!

**Comment by akirenren** [comment]
hi, i'm interested in using this mainly for the theme so i wanted to ask when it would be added

**Comment by ArtikusHG** [comment]
It seems the developers aren't really interested, however, I am currently working on automating builds of a patched version of Mull with the OLED theme and hosting these in an F-Droid repo. I will let you know when I'm done.

**Comment by akirenren** [comment]
thanks! though i don't think it's a good idea to share it on f-droid since this is another person's project, it should be fine if you just add an apk to your own github repo or add an amoled dark theme patch to the main nightly by mozilla like the original pull request did (do share an apk though lol i don't have the necessary stuff to build the original right now)

**Comment by SkewedZeppelin** [comment]
I still do plan to pull this in, the last Mull update had other fixes that were necessary due to upstream changes that took my time.

**Comment by ArtikusHG** [comment]
It would save me a lot of work if you pulled this, thanks! (I already made the patch anyway, but oh well)

**Comment by SosPosos** [comment]
> It would save me a lot of work if you pulled this, thanks! (I already made the patch anyway, but oh well)

Please, share the patch 🙏

**Comment by e-xception** [comment]
Sorry but is this still being worked on?

**Comment by SkewedZeppelin** [comment]
@e-xception not at this time

**Comment by ArtikusHG** [comment]
I finally took the time to do something about this - and I made this: https://github.com/ArtikusHG/Mull-OLEDDark

This is a GitHub Actions workflow that runs every 24 hours, decompiles and patches the upstream apk to make the default dark color scheme pitch black. It publishes the patched apks as GitHub releases, so you can import the repo into Obtainium and get updated builds like this.

This feels like a dirty hack (because it is), but the alternative is building the entire browser from scratch just to change the colorscheme - which I consider even worse.

Disclaimer: I do have to sign the patched builds with my own keys. If you don't trust me, just fork the repo and use your own keys.

Feel free to close this issue, hopefully one day upstream Firefox implements a pitch black theme.

**Comment by Fred6388** [comment]
It looks beautiful thank you. As a suggestion, It would be great to be able to add the mozilla api key for wallpapers on homepage; if possible.

**Comment by ArtikusHG** [comment]
My patchset is very small and dumb, if you want to do more significant modifications you should probably look into building Mull from scratch or upstreaming your feature request

**Comment by Fred6388** [comment]
I understand, thank you as well.

**Comment by ArtikusHG** [comment]
Closing for now as I consider this resolved.
