### ISSUE TITLE
Stability and consistency matter

### ISSUE THREAD

**Issue by Universalizer** [Divested-Mobile/Mull-Fenix#109]
### 'Probably a bug across all Firefox based forks' (noticed last 3 or 4+ update in 'Tor Alpha for Android'),

Dear Mull Developers Team, Thanks for your efforts and appreciating work for the app,

Now it occurs in Mull also, For past two update (latest 108.1.1 (21081100) ), preferences that doesn't get configured ; setting this preference gets automatically changed on every fresh restart of app or phone, before using app, each time it needs to be set.

How ?
### about:config

privacy.trackingprotection.socialtracking.enabled
 browser.safebrowsing.malware.enabled
 browser.safebrowsing.phishing.enabled
 toolkit.telemetry.geckoview.streaming

After setting this preference, exit Mull browser and again start, it works fine,

But when again exit 'especially when forced stop or restarting the phone' and cross-check it,

Again it seems the need to set this specific preference.

Hopefully future upstream may fix this bug.
Thank you.

**Comment by SkewedZeppelin** [comment]
You can't change some settings in about:config, they'll always be overwritten on restart.
That is a Fenix quirk, not Mull.

Furthermore:
ETP Strict already enables these:
```
privacy.trackingprotection.socialtracking.enabled
browser.safebrowsing.malware.enabled
```

Safe Browsing does NOT do anything in Mull or Fennec F-Droid because no Google API key:
```
 browser.safebrowsing.phishing.enabled
```

Telemetry is disabled:
```
 toolkit.telemetry.geckoview.streaming
```

**Comment by SkewedZeppelin** [comment]
All telemetry is either disabled or stubbed out. Removing the libraries is non-trivial and increases the maintenance necessary.

I recommend leaving ETP Strict and adding uBlock Origin.

Regarding CoverYourTracks, please read this: https://github.com/privacyguides/privacyguides.org/discussions/1797#discussioncomment-3721547

**Comment by SkewedZeppelin** [comment]
Don't ask to ask a question, just ask it.

**Comment by SkewedZeppelin** [comment]
https://github.com/Divested-Mobile/Mull-Fenix/discussions

**Comment by SkewedZeppelin** [comment]
https://github.com/Divested-Mobile/Hypatia/discussions
https://github.com/Divested-Mobile/CVE_Checker/discussions
https://github.com/Divested-Mobile/Maps/discussions
https://github.com/Divested-Mobile/Extirpater/discussions
https://github.com/Divested-Mobile/Mulch/discussions
