### ISSUE TITLE
Less add-ons than other mobile browsers (even with collections?)

### ISSUE THREAD

**Issue by zdat** [Divested-Mobile/Mull-Fenix#110]
I've added the "What-I-want-on-Fenix" add-on collection, but when I go to "add-ons" in Mull there is unfortunately no search icon like there is in comparable mobile browsers, and I can't scroll down as much.

Have I done something wrong or is this a limitation at the moment? Thanks.

**Comment by SkewedZeppelin** [comment]
That is the upstream Fenix limitation, no search and only first 50 are shown.

Create your own collection or find another one to get the ones you need.

But again I strongly only recommend the use of uBlock Origin.
