### ISSUE TITLE
F-droid label source code is not completely free

### ISSUE THREAD

**Issue by Mikrizi** [Divested-Mobile/Mull-Fenix#114]
Why F-droid mark Mull it: 
"the original source code is not completely free"

?

mulch webview too

**Comment by SkewedZeppelin** [comment]
Mulch has proprietary blobs from Chromium as part of Google Play Services used for things like Safe Browsing and WebAuthn

**Comment by SkewedZeppelin** [comment]
Mulch currently only contains patches from Vanadium and some from LineageOS. It previously contained patches from Bromite, but doesn't anymore.

**Comment by Mikrizi** [comment]
It's bad that DivestOS has a system webview with proprietary components, it's like a hematoma on the heart. If you add the lack of root rights, you cannot fix it by deleting it.

It is a pity to realize this, but for me it is a critical factor
