### ISSUE TITLE
All extensions present the English interface

### ISSUE THREAD

**Issue by klcb2010** [Divested-Mobile/Mull-Fenix#115]
All extensions present the English interface, even if the current language is Chinese
![Screenshot_2023-01-09-23-50-42-787_us spotco fennec_dos](https://user-images.githubusercontent.com/32628414/211349962-322e4b1c-9060-4818-b5be-ed7aba139fde.jpg)
![Screenshot_2023-01-09-23-50-14-570_us spotco fennec_dos](https://user-images.githubusercontent.com/32628414/211349978-fe39cf92-33af-4f03-8fb8-f801f9e8b687.jpg)

**Comment by SkewedZeppelin** [comment]
https://github.com/Divested-Mobile/Mull-Fenix/issues/102

**Comment by klcb2010** [comment]
> #102

I have updated some settings, but still haven't solved the problem

**Comment by SkewedZeppelin** [comment]
This is fixed in Mull v113.0.0
