### ISSUE TITLE
Firefox Sync doesn't work

### ISSUE THREAD

**Issue by 00028** [Divested-Mobile/Mull-Fenix#116]
When I try to use Firefox Sync, I get a "500 error" and cannot sync.

`n@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/app.bundle.ja.js:9:13512 diff@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/app.bundle.ja.js:9:13673 getLoad@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/app.bundle.ja.js:9:16036 getAllData@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/app.bundle.ja.js:9:24200 getFilteredData@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/app.bundle.ja.js:9:25542 flush@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/app.bundle.ja.js:9:23181 logEvent@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/app.bundle.ja.js:9:26314 logView@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/app.bundle.ja.js:9:27090 logView@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/app.bundle.ja.js:1:37891 showView/</<@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/app.bundle.ja.js:9:110916 invoke@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/appDependencies.bundle.js:84:6401 run@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/appDependencies.bundle.js:84:1809 R/<@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/appDependencies.bundle.js:99:2761 invokeTask@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/appDependencies.bundle.js:84:7019 runTask@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/appDependencies.bundle.js:84:2424 m@https://accounts-static.cdn.mozilla.net/bundle-ca5431743db94d007649461e21e3cb2d0c7f70ff/appDependencies.bundle.js:84:9056
`
![Screenshot_20230113-215754_Mull](https://user-images.githubusercontent.com/87330832/212325616-c99667f1-0e3c-4089-99a3-353bbc5d1c87.png)

**Comment by towfikomar** [comment]
![Screenshot_2023-01-16-13-13-09-03_50ecd26a21c2c56ce608de5e94733463](https://user-images.githubusercontent.com/114739840/212619347-bdb02afb-1941-43d7-b17a-37e9eb9949f6.jpg)
Same here

**Comment by hrrd** [comment]
same here. in the firefox subreddit some people reported that it works if you disable privacy.resistFingerprinting in about:config. don't know if this is risky

**Comment by MayaBi7** [comment]
> same here. in the firefox subreddit some people reported that it works if you disable privacy.resistFingerprinting in about:config. don't know if this is risky

It's worked..and it's not risky at all......by the way thanks bro👍

**Comment by SkewedZeppelin** [comment]
Do NOT disable resistFingerprinting, that is the entire point of Mull.

**Comment by MayaBi7** [comment]
> Do NOT disable resistFingerprinting, that is the entire point of Mull.

Ok.. I'm disabling it...☠️

**Comment by onkuV** [comment]
> Do NOT disable resistFingerprinting, that is the entire point of Mull.

would it be okay to temporarily disable "resistFingerprinting" just for sync sign in?

**Comment by SkewedZeppelin** [comment]
> would it be okay to temporarily disable "resistFingerprinting" just for sync sign in?

If you close out of all tabs first, then disable it, go through Sync setup, and re-enable it: yes.

**Comment by onkuV** [comment]
> > would it be okay to temporarily disable "resistFingerprinting" just for sync sign in?
> 
> If you close out of all tabs first, then disable it, go through Sync setup, and re-enable it: yes.

doing that, 

@00028 u can close this issue now

**Comment by hrrd** [comment]
is this bug reported upstream? does anybody have some infos?

**Comment by onkuV** [comment]
> is this bug reported upstream? does anybody have some infos?

a new bug report has been filed right after ur comment here
similar problem seems to occur on all firefox version when `privacy.resistFingerprinting` is set to true and multiple websites had similar problem and has already been reported on bugzilla

**Comment by okwhynot1** [comment]
> > is this bug reported upstream? does anybody have some infos?
> 
> a new bug report has been filed about the same time this issue was opened
> similar problem seems to occur on all firefox version when `privacy.resistFingerprinting` is set to true and multiple websites had similar problem and has already been reported on bugzilla
> 
> edit: 
> for more info
> https://bugzilla.mozilla.org/show_bug.cgi?id=1810741

I worked. I turned off privacy.resistFingerprinting, signed in and then turned it on again. Thanks!

**Comment by tuxayo** [comment]
I worked now for me a few days ago on two phones. Without touching resistFingerprinting. Can someone else confirm?

**Comment by hrrd** [comment]
Worked for me too a few days ago. Can confirm. With privacy.resistFingerprinting.

**Comment by towfikomar** [comment]
> I worked now for me a few days ago on two phones. Without touching resistFingerprinting. Can someone else confirm?

Yes it's working now

**Comment by tuxayo** [comment]
Lets close then :partying_face:  cc @00028 @SkewedZeppelin
