### ISSUE TITLE
Add ability for container-extension

### ISSUE THREAD

**Issue by j-nicolas** [Divested-Mobile/Mull-Fenix#117]
Hi! A great feature regarding privacy on firefox for PC is a container-ization of tabs
like this: https://addons.mozilla.org/en-US/firefox/addon/temporary-containers
If it was possible to make that work on Mull as well, that would be great!
(Or a similar extension - there are alternatives.)
Best regards - Nicolas
(BTW - how to add label:enhancement?)

**Comment by SkewedZeppelin** [comment]
All websites are already isolated via first party isolation.
