### ISSUE TITLE
can't upload or edit images

### ISSUE THREAD

**Issue by Vardor** [Divested-Mobile/Mull-Fenix#118]
In sites like twitter or pixelfed when I upload and edit an image it shows just in a single color, no image is showed at all. When I try to edit, result is the same.

![Screenshot_20230204_161321_Mull](https://user-images.githubusercontent.com/39595481/216785550-c02dac8a-6082-4637-924d-09017043fb02.jpg)

**Comment by SkewedZeppelin** [comment]
This is a known upstream issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1801733

RFP blocks canvas access and you can't make a per site exception.

**Comment by DuendeInexistente** [comment]
> This is a known upstream issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1801733
> 
> RFP blocks canvas access and you can't make a per site exception.
> 
> Use a different web browser for that website, pick one from here: https://divestos.org/index.php?page=browsers

Then it shouldn't be on by default. There's making consesions for security and there's making a bunch of websites lack basic functionality.
