### ISSUE TITLE
Remove ESNI from userjs-brace.js

### ISSUE THREAD

**Issue by N8Z7JMYLU** [Divested-Mobile/Mull-Fenix#12]
Support for ESNI has been pulled since version 85.0. I suggest removing _pref("network.security.esni.enabled", true);_ from [userjs-brace.js](https://github.com/Divested-Mobile/Mull-Fenix/blob/master/preferences/userjs-brace.js)

Mozilla plans to replace this feature with ECH: https://blog.mozilla.org/security/2021/01/07/encrypted-client-hello-the-future-of-esni-in-firefox/

**Comment by SkewedZeppelin** [comment]
Done.
Thanks!
