### ISSUE TITLE
Ability to install extensions from file and outside Mozilla addon store

### ISSUE THREAD

**Issue by DraconicNEO** [Divested-Mobile/Mull-Fenix#120]
Hi I think we should add the ability to install extensions from outside of the addon store either from outside web sources like GitHub or gitlab (not restricted to these two of course) or from downloaded xpi files.

The reason for this is that Mozilla's model is extremely restrictive and doesn't provide a way for users to install their own extensions from outside of the store, only allowing users to import collections from the store.

**Comment by SkewedZeppelin** [comment]
Out of scope
