### ISSUE TITLE
Sometimes unable to enter text into websites

### ISSUE THREAD

**Issue by Apacelus** [Divested-Mobile/Mull-Fenix#121]
Sometimes I am unable to enter text into websites, i.e
 search fields, comments, etc...
Only closing and reopening the app fixes this issue, although temporarily.

This issue is not new and has been happening since 108.0

Unfortunately I cant reliably reproduce this issue and I'm not sure where to find any kind of logs.

I use a Oneplus 9 Pro with the latest LineageOS (Android 13), rooted. The keyboard is Openboard, which has not had this kind of issue in any app outside of Mull.

**Comment by SkewedZeppelin** [comment]
This is a known issue that happens on some devices, cause unknown: https://gitlab.com/divested-mobile/mull-fenix/-/issues/17

Try a different keyboard maybe. I've never been able to reproduce it myself.

**Comment by Apacelus** [comment]
Is there any way to check the logs somewhere? I could do that the next time I get this bug

**Comment by Apacelus** [comment]
So I actually havent had this bug anymore for a while and I think its probably been fixed (don't know if in Mull or upstream)

**Comment by SkewedZeppelin** [comment]
Why did you close this? Is it no longer reproducible?

**Comment by Apacelus** [comment]
Yes, as mentioned I am not able to reproduce it anymore

**Comment by SkewedZeppelin** [comment]
Oh weird, it didn't show for somereason, maybe delayed on GitHub's end.
Glad to hear
