### ISSUE TITLE
Swipe close the same as close app in menu

### ISSUE THREAD

**Issue by Mr-Bajs** [Divested-Mobile/Mull-Fenix#123]
I suppose this should be done upstream, but things seams slow at the Mozilla.

It would be great closing the app by swipe closing, does the same thing as closing the app in the menu. I usally want the app to be cleared of all data when closing the app. But the habit of closing apps in Android is atleast by me done by swipeing. Closing through the menu is unintuitive on a touch device such as a phone/tablet.

**Comment by SkewedZeppelin** [comment]
out of scope, and probably conflicts with the caching mechanism
