### ISSUE TITLE
Alternative search engines

### ISSUE THREAD

**Issue by alas-he** [Divested-Mobile/Mull-Fenix#13]
It would be great to have alternative privacy-friendly search engine options included instead of the default list. Personally, I'd love to see StartPage included as a replacement for Google. 

I know it's possible to manually add search engines, but Fenix doesn't provide/allow search suggestions with custom-added search engines. I'm currently using DuckDuckGo as default search since it is more private and provides suggestions, but the results are just not as good as Google/StartPage. (Sorry I'm not a developer so can't offer a solution or help to make this happen, just sharing my experience as a user ☺)

On a related question: Is there any way to save custom settings for search engines like StartPage or DDG when using Mull - e.g. preserving cookies for those sites without having to keep all cookies?

**Comment by Snub90** [comment]
@alas-he Yes, you can save custom settings of search engine without saving cookies. I use ddg. You need to convert ur bookmarklet URL to a search string. Reply i u wanna know how.

**Comment by chris122380** [comment]
> @alas-he Yes, you can save custom settings of search engine without saving cookies. I use ddg. You need to convert ur bookmarklet URL to a search string. Reply i u wanna know how.

I've been searching through on how to add dark mode to duckduckgo's URL. I know there is a duckduckgo URL Parameters page but can be quiet confusing, plus I don't know the default URL Mull is using for duckduckgo search.  I know this can be done from settings on the search engines website however if I clear browser data (for security reasons) those settings would be lost. Hence why I'd like to be able to add a custom dark mode duckduckgo search engine in the Mull settings.  

It might need to be a separate issue but it would be nice to have dark mode versions of search engines in Mull (where the URL Parameter would allow it). Since privacy.resistFingerprinting settings would prevent many of these search engines from detecting that the browser is using the dark theme (issue 10 and 22).

**Comment by SkewedZeppelin** [comment]
@chris122380 
You should be able to add `https://duckduckgo.com/?kae=d&q=%s` in the Settings > Search > Add search engine

**Comment by Snub90** [comment]
@chris122380 As mentioned by @SkewedZeppelin, you can paste this search string for your custom search engine setting (dark mode on ddg). https://duckduckgo.com/?kae=d&q=%s

**Comment by Snub90** [comment]
`https://duckduckgo.com/?kae=d&q=%s`

**Comment by proletarius101** [comment]
However, you can't get search suggestions from custom search engines. So it would be much helpful if we can add it to the built-in list.

**Comment by SkewedZeppelin** [comment]
Steps to add a search engine:
- Copy one from [here](https://github.com/mozilla-mobile/android-components/tree/main/components/feature/search/src/main/assets/searchplugins)
- Put it [here](https://github.com/Divested-Mobile/Mull-Fenix/tree/master/a-c-overlay/components/feature/search/src/main/assets)
- Add it [here](https://github.com/Divested-Mobile/Mull-Fenix/blob/master/a-c-overlay/components/feature/search/src/main/assets/search/list.json)
- Make a pull request.

I'll test it and upstream it to [fennecbuild](https://gitlab.com/relan/fennecbuild), or make the merge request there and I'll still test it.

**Comment by proletarius101** [comment]
@SkewedZeppelin Thansk. I submitted an MR: https://gitlab.com/relan/fennecbuild/-/merge_requests/14

**Comment by Snub90** [comment]
> It might need to be a separate issue but it would be nice to have dark mode versions of search engines in Mull (where the URL Parameter would allow it). Since privacy.resistFingerprinting settings would prevent many of these search engines from detecting that the browser is using the dark theme

You're right !! I've always wanted to use Brave Search with dark mode but privacy.resistFingerprinting prevents it & using it with Dark Reader addon makes it way too slow. I'll never toggle off privacy.resistFingerprinting option. So, is there any other way to use the dark mode on Brave Search (without any addon) ?

**Comment by SkewedZeppelin** [comment]
https://gitlab.com/relan/fennecbuild/-/merge_requests/21
