### ISSUE TITLE
Mutual tls client certificates

### ISSUE THREAD

**Issue by ippocratis** [Divested-Mobile/Mull-Fenix#130]
I selfhost various services behind reverse proxy and mutual tls so that they wont respond to clients unless they recieve a client certificate.
I have installed the PKS12 cert on the device in the user store.
Chromium based browser can pick the cert as they use the android cert store.
Firefox android uses his own cert store.
Fennix (firefox android) does not support client certificates https://github.com/mozilla-mobile/fenix/issues/13988
Desktop does.

It would be great if Mull diferentiate on that matter and somehow provide a way to add the client certificates to the browsers cert store

I have tried to manually add the p12 cert to cert9 and key4 db's with pk12util `pk12util -i /path/to/my-cert.p12 -d sql:path/to/db` and certutil but doesn't seem to work 

Thanks and keep up

**Comment by SkewedZeppelin** [comment]
out of scope
