### ISSUE TITLE
Custom search suggestions url

### ISSUE THREAD

**Issue by PH-68** [Divested-Mobile/Mull-Fenix#131]
Allow custom search suggestions url to be set
![Screenshot_20230526_011554_Mull](https://github.com/Divested-Mobile/Mull-Fenix/assets/58099156/d8f254cd-43ea-434f-8121-30d612f993fc)

**Comment by SkewedZeppelin** [comment]
out of scope: https://github.com/mozilla-mobile/fenix/issues/7866
