### ISSUE TITLE
refresh rate on Samsung S22U Enynos

### ISSUE THREAD

**Issue by catbabylon** [Divested-Mobile/Mull-Fenix#132]
Phone is capable of up to 120hz refresh which works fine on Firefox and on the fork Iceraven, but on Mull it seems to default to 60hz as there is a noticable judder when scrolling.

I had assumed it was something at Samsung's end where only specific known apps would make use of the higher refresh, but given that Iceraven, a niche fork works fine, I wondered if it was something in the code that could be tweaked in Mull to resolve it?

**Comment by SkewedZeppelin** [comment]
Please read through the known issues before hand:
https://divestos.org/pages/broken#mull
> Refresh rate is capped to 60hz due to resist fingerprinting. Please do not disable RFP.
