### ISSUE TITLE
Dark reader does not work optimally 

### ISSUE THREAD

**Issue by richie3011** [Divested-Mobile/Mull-Fenix#133]
Sometimes dark reader does not work well in Mull. For example in Reddit, the comment section still in white.Hope u fix it

Thx!

**Comment by SkewedZeppelin** [comment]
Why did you close this?

**Comment by SkewedZeppelin** [comment]
https://divestos.org/pages/broken#mull
> Dark mode for websites is disabled due to resist fingerprinting. Please do not disable RFP.
