### ISSUE TITLE
JPEG-XL/JXL image rendering not working 

### ISSUE THREAD

**Issue by exalented** [Divested-Mobile/Mull-Fenix#134]
Attempting to enable JXL image rendering (part of Firefox nightly experimental) still does not render JXL images in Mull.

Steps:
1. about:config > image.jxl.enabled
2. Toggling on
3. Goto https://jpegxl.info/test-page/
4. Observe image not rendered on the left

Performing these same steps yields JXL images being rendered just fine on Firefox nightly 116.0a1 from the play store.

**Comment by SkewedZeppelin** [comment]
I mean... this isn't nightly.

**Comment by exalented** [comment]
Apologies. I was under the impression Mull included experimental components. Would it then not be appropriate to remove the toggle until it's properly added?

**Comment by SkewedZeppelin** [comment]
Why would I remove the hidden toggle?

Mull tracks stable, Mull ships what stable ships, Mull makes small maintainable changes on top.

**Comment by exalented** [comment]
Sure. I yield. It's not a big dealio. Thx
