### ISSUE TITLE
 The latest version of Mull Browser (114.2.0) cannot be used at all on the latest version of OnePlus 9_divested-20.0-20230621 system, completely unable to access any websites.

### ISSUE THREAD

**Issue by Subtly7360** [Divested-Mobile/Mull-Fenix#137]
The latest version of Mull Browser (114.2.0) cannot be used at all on the latest version of OnePlus 9_divested-20.0-20230621 system, completely unable to access any websites. However, Fennec F-Droid can access web pages normally. Fennec F-Droid was downloaded from the system's built-in F-Droid, which proves that the network is functioning properly, and the issue lies with Mull Browser.

The model of the phone is LE2110 .
Android version : 13 .

**Comment by SkewedZeppelin** [comment]
https://divestos.org/pages/broken#mull
> On DivestOS 19.1 and 20.0 the initial install of Mull will not have Internet access, go to its `App info` screen then `Mobile data & Wi-Fi` and enable `Allow network access`.
