### ISSUE TITLE
Mull not showing the correct system time in the whoer.net test.

### ISSUE THREAD

**Issue by duke1921** [Divested-Mobile/Mull-Fenix#140]
![image](https://github.com/Divested-Mobile/Mull-Fenix/assets/8713541/43318b78-c4e0-464c-8cc7-65948bbe7222)

Mull not showing the correct system time in the whoer.net test. It's showing GMT +00 time. Please see image: https://imgur.com/a/5HVJ552

The device is Redmi K50i
MIUI Global 14.0.2
Android version 13

**Comment by duke1921** [comment]
![image](https://github.com/Divested-Mobile/Mull-Fenix/assets/8713541/04bdae4c-8988-473e-81e1-b2c3c3dfc204)

**Comment by SkewedZeppelin** [comment]
timezone is spoofed to UTC by resistfingerprinting.
