### ISSUE TITLE
Captcha does not appear when logging in bitwarden

### ISSUE THREAD

**Issue by radityajayawardana** [Divested-Mobile/Mull-Fenix#141]
The bitwarden login captcha does not appear, this problem also occurs in Firefox and iceraven browsers. The problem occurs on Redmi 9C device, with android 10 version, and MIUI 12.0.14

**Comment by SkewedZeppelin** [comment]
I don't have a Bitwarden account so I can't test this.

You can try maybe the WebGL step here: https://divestos.org/pages/broken#mull

But if you say it happens on official Firefox too then maybe contact Bitwarden support?
