### ISSUE TITLE
Can we get the option to add more shortcuts on the homepage without swiping left?

### ISSUE THREAD

**Issue by Aryan-Chauhan** [Divested-Mobile/Mull-Fenix#147]
![Screenshot_2023-08-19-16-31-30-76_9c7ad408470e52983cc8816adf9ff347.jpg](https://github.com/Divested-Mobile/Mull-Fenix/assets/91815107/7769477f-1273-45e9-a981-4cc3920d1296)

**Comment by SkewedZeppelin** [comment]
out of scope

**Comment by Aryan-Chauhan** [comment]
> out of scope

Any chance of reconsideration?

(I know, upstream issue thing, but Iceraven did it, can you take a look at their source code & implement it on Mull?)
