### ISSUE TITLE
"Playback disabled" while trying to use Spotify web app

### ISSUE THREAD

**Issue by stianhoiland** [Divested-Mobile/Mull-Fenix#149]
I wanted to use the Spotify web app to listen to some tunes on my "unphone", but got this error message:

![IMG_7681](https://github.com/Divested-Mobile/Mull-Fenix/assets/2081712/1ffa9a47-c464-4b8d-9544-68678a8b7960)

I'm guessing that this could very well be a feature of Mull, not a fault, but regardless I would like to understand what is causing this to occur. Maybe I can fix it, maybe not. Thanks!

**Comment by SkewedZeppelin** [comment]
DivestOS and Mull do not support the use of proprietary Google Widevine DRM.

**Comment by stianhoiland** [comment]
Ah, thank you!
