### ISSUE TITLE
Dark Reader breaks Mull

### ISSUE THREAD

**Issue by techguyone** [Divested-Mobile/Mull-Fenix#150]
I'm using a Samsung S23+ mull (android) version 116.3.0

I've been pulling out my hair for the last few hours trying every combination known to man to stop the 'Connection is not secure' from coming up.

The only thing I've seen as a constant is if you do the add-on Dark Reader then the first sign after that is that you can't click on any of the results the search engine makes (does dark reader do some kind of overlay?) then shortly after that you get the good old 'Connection is not secure' at this point, even if you remove Dark Reader it doesn't make the issue go away.

It may be that my findings are just spurious but I'd love to be able to just use the browser without doing cartwheels to get it to just work.

I just wish mull had a in-built system wide dark mode.

**Comment by SkewedZeppelin** [comment]
This is documented on the news page: https://divestos.org/pages/news#2023-08
And on the browsers page: https://divestos.org/pages/browsers#fenix-based
And reported repeatedly here: https://gitlab.com/divested-mobile/mull-fenix/-/issues/82
