### ISSUE TITLE
[Feature Removed] Long pressed a video to get option to copy its url

### ISSUE THREAD

**Issue by aicynide** [Divested-Mobile/Mull-Fenix#152]
Are you kidding me? Its the only feature I use Mull for

**Comment by aicynide** [comment]
Bring back this feature please

**Comment by SkewedZeppelin** [comment]
I don't add or remove features, Mozilla does.

But this kind of option can be disabled by the website itself.
Try setting `dom.event.contextmenu.enabled` in `about:config` to false.

**Comment by aicynide** [comment]
Not working

**Comment by SkewedZeppelin** [comment]
works just fine for me without any changes: 
![Screenshot_20230825-031210_Mull](https://github.com/Divested-Mobile/Mull-Fenix/assets/8296104/9e994ea8-5d4e-4696-8d8c-cf2949a91bd4)


like I said, the website you're using is likely blocking it or using a custom video player
