### ISSUE TITLE
Freezing randomly

### ISSUE THREAD

**Issue by TheRealOne78** [Divested-Mobile/Mull-Fenix#156]
For some reason, since I installed Mull (about two weeks ago), Mull keeps freezing randomly. I can scroll the pages, but I cannot interract with them (IE Tap an anchor, tap a button, refresh, play audio in the media player, etc) and loading may also freeze.

I downloaded this on F-Droid from the F-Droid repository with target arch `arm64-v8a`.

Current build is 116.3.0 (latest at the time of writing this)

Running Android 12 with Samsung ROM on Samsung Galaxy A42 5G.

**Comment by SkewedZeppelin** [comment]
https://divestos.org/pages/broken#mull
> Dark Reader is known to be incompatible with the Mull changes and will cause signficant breakage/slowdowns.

Do you have dark reader installed?

**Comment by TheRealOne78** [comment]
Yes I do
