### ISSUE TITLE
Why is the number of screen touchpoints being spoofed to zero?

### ISSUE THREAD

**Issue by t3dium** [Divested-Mobile/Mull-Fenix#16]
Surely this'd make the browser extremely fingerprintable when using an android user agent + screen resolution...

**Comment by SkewedZeppelin** [comment]
That is privacy.resistFingerprinting.
This should probably be reported upstream to gecko.
Also slightly relevant: https://github.com/mozilla-mobile/fenix/issues/21225

**Comment by SkewedZeppelin** [comment]
> Surely this'd make the browser extremely fingerprintable

By itself maybe, but more users using Mull is more users in the same buckets.

**Comment by t3dium** [comment]
> but more users using Mull is more users

Maybe so, but the sole percentage of users using even just firefox is still only a couple percent as opposed to other browers. Mull, even less so. I've tested this issue on other firefox browser for e.g fennec, and it didn't come up.

This can easy be fixed by replacing privacy.resistFingerprinting with a browser addon like canvasblocker or chameleon, in which case canvas and other data can be spoofed whilst keeping touchscreen info.

**Comment by SkewedZeppelin** [comment]
> fixed by replacing privacy.resistFingerprinting

Not going to happen.
