### ISSUE TITLE
Pages not rendering/scrolling when history/cookies cleared.

### ISSUE THREAD

**Issue by anxiouslelimo** [Divested-Mobile/Mull-Fenix#160]
This weird bug started happening with the 117.0.1 (arm64) version. As the browsing history/cookies is cleared from settings background/foreground tabs doesn't load, scrolling stops, parts of pages become blank/white, links become non-clickable.

**Comment by SkewedZeppelin** [comment]
I cannot reproduce this.

Clearing data while tabs are open can prevent data from really being cleared, hence why the clear page has an option to close open tabs.

But I'll leave this open for now.

You might want to test and see if you can reproduce this under official Firefox.

**Comment by SkewedZeppelin** [comment]
fwiw I had uBO installed when I tried to reproduce this

uBO will block page loading when it itself is (re)loading, maybe related

**Comment by SkewedZeppelin** [comment]
sure, feel free to re-open if it happens again
