### ISSUE TITLE
does telemetry work in built-in add-ons?

### ISSUE THREAD

**Issue by Nidrop** [Divested-Mobile/Mull-Fenix#17]
`about:support` reports that **Mozilla Android Components - Ads Telemetry** and **Mozilla Android Components - Search Telemetry** are enabled

**Comment by SkewedZeppelin** [comment]
They are disabled by default.

**Comment by Nidrop** [comment]
even if they are enabled, they don't send telemetry, right?
<details>
  <summary>image of about:support</summary>
  <img src="https://user-images.githubusercontent.com/38117732/142625541-b54078e7-57de-4403-bc83-06e174cfeb34.png">
</details>

**Comment by Nidrop** [comment]
@SkewedZeppelin It haunts me. if they are disabled by default as you say. Why does `about:support` say otherwise? (picture in the previous comment)
