### ISSUE TITLE
ESET Anti-Phishing - "No supported browser installed"

### ISSUE THREAD

**Issue by Obegg** [Divested-Mobile/Mull-Fenix#172]
I'm using ESET Anti-Phishing feature on my phone and it works fine with Firefox,
but with Mull it doesn't work.

**Comment by SkewedZeppelin** [comment]
Because you have to rely on:
- them correctly implementing the actual mechanism to decrypt/re-encrypt traffic and uphold all the existing certificate verification and cipher management assurances
- them not abusing this ultimate power to siphon off your browsing history

**Comment by SkewedZeppelin** [comment]
> what is the ideal solution for this case

You can block phishing websites without letting an app on your phone MITM connections, see DNS based services such as:
- https://quad9.net/
- https://www.dns0.eu/zero

> Do you even need Anti-Virus in your phone

Noting the bias of having my own anti-malware app, I honestly think they are not necessary at all.

**Comment by SkewedZeppelin** [comment]
@Obegg 
but does your pi-hole work when you are not at home?

And even then, I'd still recommend using such a DNS as the upstream for your pi-hole, unless you're already running your own recursive resolver.

**Comment by SkewedZeppelin** [comment]
If you're using Cloudflare, they do actually have a malware blocking variant at 1.1.1.2
