### ISSUE TITLE
"Failed to query add-ons," error 

### ISSUE THREAD

**Issue by daffydock** [Divested-Mobile/Mull-Fenix#173]
Hi, 

I noticed that Mull, after a recent update would not allow me to get to the add-ons page.  I needed to disable an add-on but in general I cannot see my installed add-ons, despite them working normally otherwise. 
I cannot install or disable add-ons via the usual way. I can't install add-ons period. 

I am aware that side-loading was removed  a couple up FF updates ago but I thought that at least I would be able to get at some of them using my own collection but that also does not work. Tried it with my own and other people's collections. I get the same error, nevertheless. If anything, I have not seen it get mentioned anywhere, and was hoping to see if you may be able to shed some light into it. 

I get a, "Failed to query add-ons," error.
Checked with other forks and this seems to be an upstream issue. Since I have seen it on SmartCookieWeb Preview as well as Iceraven. Tried downloading the lastest FF Beta (118.2) and I am able to download and install add-ons straight from the AMO page. 

Any insight or fix would be appreciated. Thank you.

**Comment by daffydock** [comment]
Update: For what is worth, I tested with latest Nightly, Ver 121.+ and add-ons work straight out of the box as well. I am able to download straight from the regular add-on page. Upgraded to latest Mull 119.+ and I still get the same error.

**Comment by SkewedZeppelin** [comment]
are you using any local VPN? custom DNS? adblocker?

**Comment by daffydock** [comment]
I am using a VPN. DNS is per browser, but in this case, no. 
Also, on the same phone, on my VPN, I have tested Nightly and Beta and even the newest IceRaven. Add-ons work as expected, except that Nightly works even better, since out of the box I was able to install an add-on usually not optimized for mobile without issues from their site. Previously I would have had to directly install the xpi file myself. Mozilla's initiative, to be able to install more add-ons seems to be coming to fruition.

Regularly, I do not touch Beta or Nightly or even Iceraven, I use your browser due to the enhanced privacy. I also use CookieWeb Preview since I like how it handles Add-ons and both browsers yield this error. Despite both being on 119+

**Comment by daffydock** [comment]
Sure. I can try these. One question though before I do. Is there a difference between your ARMv8 and ARMv7 builds? On the partner's phone, ARMv8, addons work out of the box, like they usually have.

While on my phone using ARMv7, it fails, getting the error on the issue. Both on fresh installs and all network settings/VPN/etc are the same.

**Comment by SkewedZeppelin** [comment]
There are no differences between the different architecture builds.

**Comment by daffydock** [comment]
I did not perform the changes. As it seems none of them will fix the current issue. 

As stated previously, I also use CookieWeb Preview as a secondary browser and it too was having the same issue as Mull. Touched base with Dev and he proposed and just updated his browser to latest, Ver.120+ and that fixes the add-on problem. Out of the box. 

I posit the matter was on Mozilla's end, them changing something which conflicted with at least some previous versions. 

Perhaps when Mull gets updated to Ver.120+ the issue will be fixed like it was in CWP.

**Comment by daffydock** [comment]
Update: Updated to Ver.120. Go into *Add-ons* and I no longer get the error. However, no addons show up. 

Instead, I just see the *find more addons* button. You click on it and it takes you to the AMO where you can click on *Install* to install addons. However, instead of installing --even on the mobile page-- the browser does not recognise the XPI. So it just downloads it. Tried this with a number of know addons that work on FF mobile. 

Adding my own collection, or anyone else's, for that matter does not change anything. 

Unfortunately, it still does not work. Despite working on say, FF Nightly or CookieWeb Preview.

**Comment by SkewedZeppelin** [comment]
Thanks for testing.

Still bizarre that it happens. :frowning_face:

**Comment by dikiaap** [comment]
Oh, it was Mull issue. Can confirm I can't install the XPI through AMO page where it says, "No app found to open xpi files". And I was wondering how people able to use and install the add-ons through AMO again instead of Mozilla's recommended list in v120 and I tought it was on AMO's side.

**Comment by daffydock** [comment]
Tried on 120.1, unfortunately, issue remains.

**Comment by SkewedZeppelin** [comment]
@zutzo 
please read above, that is not what this issue is about.
what you mention is a separate issue already documented on the website

**Comment by daffydock** [comment]
Updated to Ver. 121, and Add-Ons work out of the box. 
Guess we can now consider the issue resolved. 

Odd issue but at least it is now, "fixed."
Cheers, and Happy Holidays. 

Closing.
