### ISSUE TITLE
Is this an upstream issue? (About:config language setting overwrite)

### ISSUE THREAD

**Issue by DKB-91** [Divested-Mobile/Mull-Fenix#176]
It has come to my attention that the arkenfox setting no longer sticks upon opening the browser.

Instead of making me blend with other en-US, en users, intl.accept_languages changes to en-US, it

It might be because I'm not an English speaker and thus I have my device set on my native language, this has not been a problem until recent versions. (it was already 118.0.0 when I noticed it)

To note I have never changed Mull Language over to Italian, and my device never influenced accept_language until recently. 

Brave and the now Cromite don't have this issue, regardless of their language settings. (well, they leak when Brave is set not to resist language FP, and Cromite is set to Italian/Device language, but that is easy to fix)

Since from my limited understading of Firefox's fingerprinting protection, this does make me stand out from other users and harms me, correct?

I can't exactly change my phone main language without causing other problems, so if this is an upstream issue, I guess I'm SoL, aside going into about:config and resetting the value every time I boot the browser?

**Comment by SkewedZeppelin** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1765375

> resetting the value every time I boot the browser?

I wouldn't bother, as it may still reset simply when multitasking.

**Comment by DKB-91** [comment]
Yeah I've closed when I found out more in my spare time.

Hope this get fixed but sadly I don't have much faith in upstream Mozilla, be it desktop or mobile.

Unaware multitasking also changes the value, shame as this is the only android Gecko browser worth using.
