### ISSUE TITLE
Unable to use Mull entirely

### ISSUE THREAD

**Issue by Yaanu** [Divested-Mobile/Mull-Fenix#182]
I'm using Mull 120.0.0 (Build #21200020) on a Pixel 2 XL (taimen) running DivestOS 20 (20-20231110-dos-taimen).

For whatever reason, attempting to use Mull has resulted in nothing but timeout errors, effectively rendering it useless. I'm completely lost as to how or why this could be happening, as well as how to fix the problem myself. The suggestions offered through [the Known Issues list](https://divestos.org/pages/broken) don't solve the problem, and the official tools for USB debugging via Firefox aren't working, as pages time out entirely and nothing can be loaded by the desktop browser. 

Are there any logs that I can actually look at to investigate the issue, or is there some other configuration of _about:config_ toggles that I can set to fix this?

**Comment by SkewedZeppelin** [comment]
Can you confirm it network permission is granted and no network restrictions are set?
Network permission is here: App info > Permissions > Network
Network restrictions are here: App info > Mobile data & Wi-fi


Mull is working just fine on my taimen, same versions.

**Comment by Yaanu** [comment]
> Can you confirm it network permission is granted and no network restrictions are set? Network permission is here: App info > Permissions > Network Network restrictions are here: App info > Mobile data & Wi-fi
> 
> Mull is working just fine on my taimen, same versions.

Well, damn. Turns out "Allow network access" was disabled. I had no idea that was a thing at all.
Thanks for the heads up! It's all running just fine now.
