### ISSUE TITLE
libredirect would be a great extension to be added to mull browser

### ISSUE THREAD

**Issue by leao-nardo** [Divested-Mobile/Mull-Fenix#185]
https://github.com/libredirect/browser_extension

**Comment by SkewedZeppelin** [comment]
If you want it, then add it.
But I do not recommend any extensions except for uBlock Origin.

**Comment by leao-nardo** [comment]
https://addons.mozilla.org/pt-PT/firefox/addon/libredirect/

**Comment by leao-nardo** [comment]
> If you want it, then add it. But I do not recommend any extensions except for uBlock Origin.

thats the problem i cant add it . i will open an issue too about how dificult is to add and extension in mull . typing right now

**Comment by SkewedZeppelin** [comment]
You need to be on the latest version 121 to add more extensions.

**Comment by leao-nardo** [comment]
> You need to be on the latest version 121 to add more extensions. If you still can't add it on 121, then the addon developer needs to mark the addon compatible. This is not a Mull issue.

just checked , its on 117 . will try to update . 

also in other phone i installed mull on island (dont know if made a diference) but the than tried to install the current version from droid-fy outside the island . but it doesnt finishes install (neither fdroid or izzid version )

**Comment by leao-nardo** [comment]
> You need to be on the latest version 121 to add more extensions. If you still can't add it on 121, then the addon developer needs to mark the addon compatible. This is not a Mull issue.

just updated and instaled , so simple and fast , and its working . great . im closing and hope next people searching now just found this
