### ISSUE TITLE
Still logged into Twitter after closing / cleaning browsing data

### ISSUE THREAD

**Issue by nicojx** [Divested-Mobile/Mull-Fenix#187]
On Android Mull, I logged into Twitter, closed the browser (with Clear-everything-on-close on), reopened and went to x.com, to find I was still logged in. I cleared all browsing data manually, closed and reopened the browser, and was still logged in. I disabled uBlock Origin, same problem.

Mull version: 121.0.0 (Build #2120020), 1955f8455f+ GV: 121.0-20231221120431, AS: 121.0

Settings are as follows:
Tabs -- close after one day
Logins and passwords -- Ask to save and Autofill in Mull (with Twitter password saved)
Private browsing -- Open links in a private tab
HTTPS-Only Mode -- On in all tabs
Enhanced Tracking Protection -- Strict
Delete browsing data data on quit -- On

Add-ons: uBlock Origin: enabled and Run in private browsing

**Comment by SkewedZeppelin** [comment]
You need to use the quit button.

**Comment by nicojx** [comment]
Sorry, I should have said: I used the Quit button. I tried several times, same result. (strangely now, as I write this, I can't reproduce it, despite not having changed anything)
