### ISSUE TITLE
Softbrick by modifying `about:config` - How to reset individual settings via `adb`?

### ISSUE THREAD

**Issue by leehyunkeun** [Divested-Mobile/Mull-Fenix#189]
I have modified an `about:config` setting and now tabs are no longer loading, including any of the `about` pages, meaning that the browser is effectively bricked.

Is there **any** way to read out `about:config` settings e.g. via `adb` (similar to the list of important changed configurations as displayed on the `about:support` page) and reset selected ones without having to reset/reinstall the entire app?

The last options modified right before the brick belong to the `browser.cache` group, so I am fairly certain which settings need to be reset in order to unbrick the browser.

**Comment by SkewedZeppelin** [comment]
No, your only option is to wipe app data.

**Comment by leehyunkeun** [comment]
Are you serious?

Surely, there must be a way to access `about:config` via `adb`.

Where exactly are these settings stored? Isn't there something like a `prefs.js` or some XML file that one can modify to reset individual settings? AFAIK, this is no problem whatsoever on desktop versions.

**Comment by leehyunkeun** [comment]
How did you build this fork and configure all the `about:confg` settings without knowing? Also, the device in question is not rooted either.

**Comment by SkewedZeppelin** [comment]
Where the files are compiled in is completely different than where they are stored on device in userdata partition.

And if you don't have root, then it is guaranteed you can't possible fix it.

Users can't edit private app data, which is where these settings are saved.
