### ISSUE TITLE
Darksky.net doesn't show the openstreetmap radar information

### ISSUE THREAD

**Issue by Rochey** [Divested-Mobile/Mull-Fenix#19]
I've installed Mull browser from F-Droid on my Pixel 6 running Android 12 and when I go to darksky.net the map showing your location using openstreetmap isn't shown. I've tried "UV index, precipitation radar, temperature and others" and they all don't show the map.

I've installed Fennec from F-Droid and this does show the map and the correct information.

I did have Mull installed with a few addons but I uninstalled it and got a fresh, new installation from F-Droid and tested to make sure it was still not working.

Is Mull browser blocking something that it shouldn't?

**Comment by SkewedZeppelin** [comment]
It seems to require WebGL.
Set webgl.disabled to false in about:config

**Comment by Rochey** [comment]
Hi @SkewedZeppelin , thanks for the quick reply.
I've just gone to about:config and change webgl.disabled to false but it doesn't seem to have done anything. I've quit mull browser and retried Darksy.net but have the same issue. I've rechecked the about:config setting and it says false. 
Have I made the change correctly?
Or do I have to do something to apply the new about:config?

Also, is working out what was wrong with the webpage something I could do? 
Or did you have to investigate the code to find out the issue?

Thanks again for the speedy response.

**Comment by SkewedZeppelin** [comment]
This has been documented here: https://divestos.org/index.php?page=broken#mull
