### ISSUE TITLE
Unable to install extensions

### ISSUE THREAD

**Issue by M00NJ** [Divested-Mobile/Mull-Fenix#193]
Firefox recently brought back support for more extensions on mobile. For quite some time there were only a handful of extensions available on Android, in the recomended section. But now any extension that supports Android can be installed. However not in Mull. When trying to install an extension that's not in the recomended section, it just downloads an .xpi file and if you try to install it, it gives you a 'no aplication to open this file' error. I thought this happens due to extensions not supporting Android yet, but I just tried it in vanilla Firefox (Android) and it works perfectly for all extensions I tested.

**Comment by SkewedZeppelin** [comment]
You need to update your Mull, this was fixed in v121.0.0.

This issue was also already documented in the known issues section: https://divestos.org/pages/broken#mull
