### ISSUE TITLE
Global Privacy Control header sec-gpc keeps getting deactivated

### ISSUE THREAD

**Issue by BDGreyson** [Divested-Mobile/Mull-Fenix#196]
I use to manually set privacy.globalprivacycontrol.enabled to "true", and this works in both, my desktop LibreWolf and a regular Firefox with Arkenfox without any problem.

If I do the same with Mull, it works at first, including the test website
https://globalprivacycontrol.org/
showing "GPC signal detected."

As soon as the browser is closed by any means, though, be it through system restart, app closing or the app being suspended due to inactivity by the system, privacy.globalprivacycontrol.enabled is set back to "false" again.

I'd really like it to keep its state or, even better, have an actual GUI option for it.

Mull version 122.1.0 (Build 21221020)
running on GrapheneOS (Android14) build number: UQ1A.240205.002.2024020500
HTTPS-only mode enabled in all tabs
Tracking protection set to strict

Installed Addons:
uBlockOrigin 1.55.0
LocalCDN 2.6.62

--

I'll gladly provide any more details if needed,
Thank you very much for your work!

**Comment by SkewedZeppelin** [comment]
Fenix overrides many of the Gecko settings on startup.

You can already enable properly GPC via Settings > Enhanced tracking protection > Tell websites not to share & sell data
