### ISSUE TITLE
The Ugly Logo at the app opening

### ISSUE THREAD

**Issue by Spaceshiprace** [Divested-Mobile/Mull-Fenix#197]
Please Can you fix that By editing that logo at the app opening or removing it completely because its ugly ass fuck see :

![Screenshot_2024-02-11-15-09-34-400_us spotco fennec_dos_1](https://github.com/Divested-Mobile/Mull-Fenix/assets/156727749/9713dec8-b997-43ec-b612-ae6c83a06658)

**Comment by SkewedZeppelin** [comment]
Duplicate of https://github.com/Divested-Mobile/Mull-Fenix/issues/119

**Comment by Spaceshiprace** [comment]
@SkewedZeppelin
I need to notice that I don't care about the logo it self please read the description of the issue I'm talking about the one in the screenshot that appears whenever you open the app.

**Comment by SkewedZeppelin** [comment]
That is derived form the logo though, so it is the same.

**Comment by Spaceshiprace** [comment]
> That is derived form the logo though, so it is the same.

Ah Ok, Thanks

**Comment by Spaceshiprace** [comment]
@SkewedZeppelin

I want to ask, will the logo be changed anytime soon

**Comment by SkewedZeppelin** [comment]
It is low priority.
