### ISSUE TITLE
Remove default search engines and top sites

### ISSUE THREAD

**Issue by AustralEpitech** [Divested-Mobile/Mull-Fenix#199]
This is a subset of #192.
Most of the default (impossible to remove) search engines and the pre-recorded sites in the search suggestion (amazon, facebook...) are not really aligned with the goal of privacy that this browser embraces.
Could it be possible to remove those (maybe replace the search engines by the [librewolf list](https://codeberg.org/librewolf/settings/src/commit/c242d6d6c77948451af5bd52125a8a81259a7a77/distribution/policies.json#L42)), or at least provide a way for the user to do it?
Thanks.

**Comment by SkewedZeppelin** [comment]
you can already disable any engines you don't want: settings > search > manage alternative search engines

the suggested sites are useful and I won't remove them

**Comment by shiyah** [comment]
Just wanted to note that the suggested sites were removed in Firefox Android a few months ago since they weren't being maintained:
https://bugzilla.mozilla.org/show_bug.cgi?id=1842106
https://bugzilla.mozilla.org/show_bug.cgi?id=1918346#c1
