### ISSUE TITLE
Submit to F-Droid

### ISSUE THREAD

**Issue by linsui** [Divested-Mobile/Mull-Fenix#2]
Could this be submited to F-Droid? Thanks!

**Comment by SkewedZeppelin** [comment]
@linsui 
I'd be happy to see it on F-Droid.
Maybe with an altered package ID to minimize conflict, as it is currently included as a system app in DivestOS.

Other thing, currently I rebase and force-push the repo when updating, but tag the previous version for historical purposes, that might not be suitable?

**Comment by SkewedZeppelin** [comment]
Merged into fdroiddata in https://gitlab.com/fdroid/fdroiddata/-/commit/31f408eef9411ceb6fa59e4393b35c86950232be

**Comment by linsui** [comment]
Thanks!
