### ISSUE TITLE
Failed to Install Extensions

### ISSUE THREAD

**Issue by vjrmy** [Divested-Mobile/Mull-Fenix#20]
Hi dev, recently i install Mull to 95.1.0 (Build #2951002)
but failed to install 
1. Buster: Captcha Solver for Humans https://addons.mozilla.org/en-US/firefox/addon/buster-captcha-solver/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=collection

2. Video DownloadHelper 
https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=collection

![Screenshot_20211206-113903_Mull](https://user-images.githubusercontent.com/88963059/144788459-da676d1d-6cf1-4829-a24e-efd39d933ae7.jpg)

**Comment by SkewedZeppelin** [comment]
This is probably an upstream Fenix limitation.
And I don't care about extensions except for uBlock Origin.

**Comment by vjrmy** [comment]
i heard that can install this addons on Fennec version 68.
Could you give me the Releases of Mull version 68, please?

**Comment by SkewedZeppelin** [comment]
68 is over a year old and extremely insecure.

**Comment by SkewedZeppelin** [comment]
You can get older versions of Mull by adding this repo to F-Droid:
https://divestos.org/fdroid/official-archive

I strongly advice against it.
It is not secure. It cannot be trusted. It will put you and your device at risk.

**Comment by vjrmy** [comment]
I know the risk and Thank you
