### ISSUE TITLE
Can't add Kagi as custom search engine

### ISSUE THREAD

**Issue by grahamearley** [Divested-Mobile/Mull-Fenix#201]
I'm trying to add kagi.com as a custom search engine in Mull.

For the "Search string URL" field, I added `https://kagi.com/search?q=%s`, but when I click "Save" it says "Error connecting to Kagi".

I _am_ able to configure this custom search in the regular Firefox app. Is there some privacy config I need to disable temporarily to get this to work? I played around with disabling a few privacy settings in `about:config` but nothing fixed it.

**Comment by SkewedZeppelin** [comment]
Immediately when saving?

I can add it without issue. I can't however test searching with it as it redirects to a login prompt.

**Comment by SkewedZeppelin** [comment]
Just to confirm you can access it directly?
And you're on Mull 123.1.0?

**Comment by grahamearley** [comment]
I'm on 123.0.0, don't see an update available yet in F-Droid. And yep, I can access the site directly.

I tried all these workarounds (all at once) and was unable to add it.

Then I tried wiping my browser history and that fixed it! Not sure what was going on there, but I'll close this issue. Thanks for the quick help.

**Comment by fin444** [comment]
I had a similar experience. From a fresh install, trying to add kagi gave me this error. But after clearing browsing data, it worked perfectly.
