### ISSUE TITLE
Themed icon layout busted

### ISSUE THREAD

**Issue by cjseaslug** [Divested-Mobile/Mull-Fenix#202]
![IMG_20240310_123223](https://github.com/Divested-Mobile/Mull-Fenix/assets/83566426/3ad0a1c3-6c96-4c8d-9334-9da530afe873)

Hi, just wanted to report that the themed icon appears to need some layout work to match other icons.

Android 14 (GrapheneOS)
Mull 123.0.0 (Build #21230020)

**Comment by SkewedZeppelin** [comment]
It is functioning fine there.

As for the design, see https://github.com/Divested-Mobile/Mull-Fenix/issues/119

**Comment by cjseaslug** [comment]
![image](https://github.com/Divested-Mobile/Mull-Fenix/assets/83566426/957737d2-0ea8-44e0-9e0b-f9fd6291c001)

Sorry to double-check, but is it? See attached with reference lines drawn & apparent misalignments & clipping issue circled.

**Comment by SkewedZeppelin** [comment]
neither are centered :smiling_imp:
