### ISSUE TITLE
⚠️ Secure Connection Failed | Connection is not secure 🔓 

### ISSUE THREAD

**Issue by gongoscho** [Divested-Mobile/Mull-Fenix#21]
Hello,

I have problems with sites that have a Let's Encrypt certificate! 😵‍
I get the following error when opening: Secure Connection Failed | Connection is not secure 🔓 

Testing page: https://letsencrypt.org/

**Screenshot**
<img src="https://user-images.githubusercontent.com/13180775/145371177-a557e728-f8bc-40b3-9433-bdc93388d527.png" width="200">

grEEtZ,
gongoscho

**Update**
The problem has been resolved with the update to the current version 95.1.0 (2951020). 😃

**Comment by Atrate** [comment]
The problem persists with many websites
