### ISSUE TITLE
Access to add-ons from 'preview'

### ISSUE THREAD

**Issue by Fred6388** [Divested-Mobile/Mull-Fenix#213]
Hi devs, I would like to know if it is possible to add a shortcut to the addons from the 'preview'.

![Screenshot_2024-05-06-08-56-33_1](https://github.com/Divested-Mobile/Mull-Fenix/assets/73563465/b6bf02fb-f72a-4bdf-9836-5be3f0cac62a)

It appears when you open a link from an application or a external link; it's the only feature that Kiwi has that I truly envy, but I'm not sure if it's possible in Gecko. I know this is a Mozilla thing, but I wanted to check first if you could do something about it 😊.

**Comment by SkewedZeppelin** [comment]
This would be for upstream Mozilla to fix.
