### ISSUE TITLE
image download (to system, not inside the browser) is extremely slow

### ISSUE THREAD

**Issue by firefoxlover** [Divested-Mobile/Mull-Fenix#215]
This is really strange. Using different websites, DDG, Bing and more.

I click on images they load normally, I can show the file, open in new tab.

But when downloading (save outside of app container) it takes forever and simply does not work.

125.3.0 (Build #21253020), GrapheneOS Android 14

**Comment by SkewedZeppelin** [comment]
Is this still an issue on Mull 127?

**Comment by firefoxlover** [comment]
cant reproduce
