### ISSUE TITLE
Outdated Clang

### ISSUE THREAD

**Issue by garlandeau** [Divested-Mobile/Mull-Fenix#22]
Latest Mull browser uses Clang v9.0.9 whereas official firefox for android built with v13.0.0. Unless there's a specific reason, could you build with the latest Clang?

**Comment by SkewedZeppelin** [comment]
That is the clang from the Android NDK.
Any particular reason you believe this to be an issue?

**Comment by garlandeau** [comment]
There may be some security and performance implications.
