### ISSUE TITLE
F Droid lags behind in releases for roughly month incl potential security fixes

### ISSUE THREAD

**Issue by DSDV** [Divested-Mobile/Mull-Fenix#220]
Hi 
at first let me say thank you for the project (: 
 i noticed that fdroid latest release version is  Version 125.3.0 (21253020) - Added on May 09, 2024 
while github shows three releases since than: 
v126.0.1 May 28, 2024
v126.0.0 May 16, 2024
v125.3.0-2 May 1, 2024

is it possible to add the apks to the releases so they can be obtained by apps like obtanium so users are not depended on fdroid? 

with kind regards

**Comment by SkewedZeppelin** [comment]
Use the official repo: https://divestos.org/pages/our_apps#repos
Or direct downloads: https://divestos.org/pages/our_apps#directDownloads
