### ISSUE TITLE
DOH does not resolve to designated server

### ISSUE THREAD

**Issue by Striker789** [Divested-Mobile/Mull-Fenix#230]
@SkewedZeppelin 
When configuring DOH, my DNS server does not pickup the queries. I have tried this with two DNS servers, there are no logs. 

I set custom uri, removed default provider and set trr.mode to 2/3 and there are no changes. I tested with a DNS resolver and the resolver indicates that my DNS server is 0/error. 

Is there anything I am missing? 

Thank you in advance.

**Comment by SkewedZeppelin** [comment]
You need to set `network.trr.uri` as `network.trr.custom_uri` is just used for a placeholder in the UI.

**Comment by Striker789** [comment]
@SkewedZeppelin 
Thank you very much! That solved it.
