### ISSUE TITLE
remove built in addons

### ISSUE THREAD

**Issue by rhjdvsgsgks** [Divested-Mobile/Mull-Fenix#235]
hi

i found that there is a built in addon called `Mozilla Android Components - Ads Telemetry` in addon list at `about:support` page. is it possible to patch it out at build time?

by the news of [hangout_services on chromium](https://news.ycombinator.com/item?id=40918052) recently. i would suggest also review all other built in addon

**Comment by SkewedZeppelin** [comment]
it is disabled.

**Comment by SkewedZeppelin** [comment]
it is more than one line
https://github.com/Divested-Mobile/Mull-Fenix/blob/master/fenix-liberate.patch

**Comment by SkewedZeppelin** [comment]
Again telemetry is globally disabled.
