### ISSUE TITLE
Github's "copy snippet" feature doesn't work

### ISSUE THREAD

**Issue by xyllery-7** [Divested-Mobile/Mull-Fenix#24]
This:
![gh](https://user-images.githubusercontent.com/95232743/147391676-e311a565-d8a7-49e8-8162-a76a52171137.png)

Doesn't copy the piece of text. When I try to paste it, it only gives me text I copied (manually) before:

![gh2](https://user-images.githubusercontent.com/95232743/147391719-32818c33-d2d5-43b2-94b2-48aabc37a185.png)

**Comment by SkewedZeppelin** [comment]
This is expected:
https://github.com/Divested-Mobile/Mull-Fenix/blob/master/preferences/userjs-arkenfox.js#L1303

**Comment by xyllery-7** [comment]
Thanks. Closing issue.
