### ISSUE TITLE
Does not load Instagram stores 

### ISSUE THREAD

**Issue by Striker789** [Divested-Mobile/Mull-Fenix#240]
@SkewedZeppelin 
I had been using mull for Instagram, unfortunately, lately I have realised (I cannot specify the exact time) Instagram stories had stopped loading, rather simply displays a text of the image. 

I had deleted mull, removed all extensions and tried yet there was no luck. 

Is there anything I'm missing, or is this a general issue?

**Comment by SkewedZeppelin** [comment]
I had a report of that not working recently.
Best to keep a second browser for problem websites. Pick one from here: https://divestos.org/pages/browsers

**Comment by Striker789** [comment]
@SkewedZeppelin 
Thank you for your response. 

If you don't mind to clarify, is there a possible toggle/update to allow ublock origin to block third party scripts, inline scripts, frames etc on nightly or is this feature simply just activated for Mull? 

Thank you.

**Comment by Striker789** [comment]
@SkewedZeppelin 
Changing the password fixes this issue, probably had too many browsers connected
> I had a report of that not working recently.

Most likely people also have this issue.
