### ISSUE TITLE
Can't update Mull to v 129 on DivestOS: No versions with compatible signer

### ISSUE THREAD

**Issue by jujar** [Divested-Mobile/Mull-Fenix#241]
I'm currently unable to update Mull to from version 128.0.2 to  version 129 from F-droid on DivestOS 20-20240810-dos-guacamole. Both the official F-droid app and Droid-ify give me the error that the new version is signed with a different certificate than the currently installed version. Since I can't uninstall Mull due to it being a system app, what should I do?

**Comment by SkewedZeppelin** [comment]
You need to move the DivestOS repo to the top of the list or set it as the preferred source.

**Comment by jujar** [comment]
Thank you
