### ISSUE TITLE
Spash icon need some changes

### ISSUE THREAD

**Issue by singhh9596** [Divested-Mobile/Mull-Fenix#242]
First of all I appreciate the work you putting in this app but lately the recent builds are having minor crashes (same is the case with fennec) Keeping it aside, can you do something about the slash screen logo. That fox in a sphere is not properly aligned. Instead of putting the fox logo in a circle you can simply use the logo with black background. Just like fennec.

**Comment by SkewedZeppelin** [comment]
Graphics discussion is here: https://github.com/Divested-Mobile/Mull-Fenix/issues/119

Mull should not be crashing all. It is very likely you wrongly enabled Fisison or made some other change via about:config. eg. https://github.com/Divested-Mobile/Mull-Fenix/issues/236

**Comment by singhh9596** [comment]
I guess I'll have to wait for a crash to be able to copy the
Crash logs. It's not crashing anymore whatsoever.

**Comment by singhh9596** [comment]
> Graphics discussion is here: #119
> 
> Mull should not be crashing all. Have you make enabled Fission or made some other change via about:config. eg. #236 If you didn't make any such changes please consider reporting it to Mozilla: https://bugzilla.mozilla.org/home


https://github.com/user-attachments/assets/be6e884a-54ab-468f-8f01-4fa3fb159d8b

Can't really do a

https://github.com/user-attachments/assets/944a5543-ac39-4513-98f1-beda87b28c77

nything
