### ISSUE TITLE
option to disable safebrowsing

### ISSUE THREAD

**Issue by mlario** [Divested-Mobile/Mull-Fenix#243]
Hi,

Could you please provide option to disable safebrowsing - either switch it off in user.js or provide persistent settings option

Changes in about:config get reverted after some time (after update?) so can only be fixed on your side

Mull is privacy oriented browser but connects to google for lists

Similar functionality is anyway provided by ublock origin

Thanks

**Comment by SkewedZeppelin** [comment]
Mull does not have safe browsing. This is documented here: https://divestos.org/pages/browsers

**Comment by mlario** [comment]
safebrowsing is enabled in about:config settings:

browser.safebrowsing.malware.enabled
browser.safebrowsing.phishing.enabled


old [issue](https://github.com/Divested-Mobile/Mull-Fenix/issues/30) confirms this.


So can you please provide more details to your previous answer


And in case safebrowsing is indeed enabled please provide means to disable it

**Comment by SkewedZeppelin** [comment]
Safe browsing does NOTHING without a Google API key.

**Comment by SkewedZeppelin** [comment]
You can trivially verify this, try to open this test page in Mull and notice how it doesn't get blocked because it is NOT enabled.

https://testsafebrowsing.appspot.com/s/phishing.html
