### ISSUE TITLE
Unable to add passkey with bitwarden

### ISSUE THREAD

**Issue by singhh9596** [Divested-Mobile/Mull-Fenix#247]
Not been able to successfully add a passkey with Bitwarden. Bitwarden's passkey has finally integrated with the Mull browser, which was supposed to reduce the pain of logging in with manually copy pasting or using auto-fill passwords, but unfortunately, I'm facing an issue where the process gets stuck in endless loading with the message 'waiting for input from the browser interaction...' And eventually getting failed message

Device info:
Mull browser(F-droid) - version 129.0.2 us.spotco.fennec_dos
Device: Samsung m42 android 13, pixel 8a running on android 14
![Screenshot_20241004-094926_Mull](https://github.com/user-attachments/assets/22d41f29-cca3-4fe3-b3a8-1e43a7be4d81)

**Comment by SkewedZeppelin** [comment]
> Bitwarden's passkey has finally integrated with the Mull 

It won't work until https://github.com/bitwarden/android/pull/4022 is complete.

> version 129.0.2

Please update to 131 available via https://divestos.org/pages/our_apps#repos

**Comment by singhh9596** [comment]
https://github.com/user-attachments/assets/492682ce-9b24-4981-9dd4-7a8ddf81e3e8

**Comment by SkewedZeppelin** [comment]
@singhh9596 
again, please wait on https://github.com/bitwarden/android/pull/4022

**Comment by lucasmz-dev** [comment]
@singhh9596 are you on at least android 14

**Comment by singhh9596** [comment]
> @singhh9596 are you on at least android 14

Yes, one of my device is running on Android 14.

**Comment by lucasmz-dev** [comment]
On this one you sent a screen recording of? Because that feels like some different issue; it doesn't seem to give the error I'd expect

Are you using the native beta client

**Comment by lucasmz-dev** [comment]
OK nevermind just saw the details on the issue, it won't work on the Samsung phone due to it being on 13. 14 is where Android gets proper passkey support, and that's what's getting fixed with the PR Tavi linked.

**Comment by singhh9596** [comment]
Understood. I hope the passkey works fine on A13 as well, since I wouldn't want to depend on just one device.

**Comment by lucasmz-dev** [comment]
I don't think there's much to do, would depend on Google redirecting this stuff IG. Passkeys AFAIK are purely a GMS thing in  <14.

Just again, are you using the beta native client for Bitwarden or the current one? This is getting fixed in the native client though it should come out soon sometime.

**Comment by singhh9596** [comment]
I'm using Beta native version

**Comment by SkewedZeppelin** [comment]
@singhh9596 
beta doesn't matter, the code has not been added yet

**Comment by singhh9596** [comment]
It's working on the latest build. I don't know if it's due to the latest update of bitwarden or firefox. But who cares as long as it's working
