### ISSUE TITLE
idontcareaboutcookies

### ISSUE THREAD

**Issue by basings** [Divested-Mobile/Mull-Fenix#25]
Would it be posssible to allow the idontcareaboutcookies addon to run in mull? 
idontcareaboutcookies is essential if you browse the web from a European IP. 

Iceraven supports idontcareaboutcookies and it works without problems (in my experience)

**Comment by SkewedZeppelin** [comment]
Use one of the `annoyance` lists in uBlock Origin

**Comment by basings** [comment]
I actually do but it's not quiet the same and I still get "a lot" of popups.

**Comment by rustforfuture** [comment]
> Would it be posssible to allow the idontcareaboutcookies addon to run in mull? idontcareaboutcookies is essential if you browse the web from a European IP.
> 
> Iceraven supports idontcareaboutcookies and it works without problems (in my experience)

Except annoyance blocklists and cookie protection in annoyance list of uBo, you can also use this:

https://www.i-dont-care-about-cookies.eu/abp/
