### ISSUE TITLE
(Enhancement) add mull APK to Tags/Releases.

### ISSUE THREAD

**Issue by DeanLemans** [Divested-Mobile/Mull-Fenix#253]
Please add the mull APK to the [Tags](https://github.com/Divested-Mobile/Mull-Fenix/tags)
Or use/make [Releases](https://github.com/Divested-Mobile/Mull-Fenix/releases) and add the APK there.

While I can download from fdroid those (APK) get updated slower.

And if the APK is included in the releases/tags then people can use [obtainium](https://github.com/ImranR98/Obtainium) to get the releases faster.

**Comment by SkewedZeppelin** [comment]
you can download them here: https://divestos.org/pages/our_apps
