### ISSUE TITLE
Neostore says there's a known security vulnerability

### ISSUE THREAD

**Issue by viasux** [Divested-Mobile/Mull-Fenix#254]
What's up with that?
![Screenshot_20241025-113008](https://github.com/user-attachments/assets/899f3242-7cdc-4ecf-a4e7-facb0f34c081)

**Comment by SkewedZeppelin** [comment]
Please read the news: https://divestos.org/pages/news#2024-10
> Updated Mull to [131.0.0](https://www.mozilla.org/en-US/firefox/android/131.0/releasenotes/), has 14+1+25 security fixes from the previous 129.0.2 release. In order to resolve the compilation issue introduced in 130, Mull is now compiled using Mozilla's prebuilt clang toolchain. This however is incompatible with the F-Droid.org inclusion criteria, so these updates (for now at least) will only be available via the DivestOS.org F-Droid repository. Please note, while this adds a prebuilt dependency, the result does still remain FOSS.

Use the DivestOS.org repo: https://divestos.org/pages/our_apps#repos

Please also don't use Neo Store as it doesn't have complete mirror support to offload traffic.

**Comment by bushrang3r** [comment]
I tried adding this repo in F-droid but there's an error.
https://divestos.org/pages/our_apps#repos

![Screenshot_20241031-074609_F-Droid](https://github.com/user-attachments/assets/d0b79807-4183-4624-86d6-b9bea26e7116)

**Comment by SkewedZeppelin** [comment]
@bushrang3r 
Neo Store already has the DivestOS repo in its list of included repositories, just turn it on.

**Comment by bushrang3r** [comment]
Thanks, but I'm talking about F-droid. 
I don't use Neo store.
Maybe I should report this at Divest.

**Comment by SkewedZeppelin** [comment]
@bushrang3r be sure you're adding the correct url, it is: https://divestos.org/apks/official/fdroid/repo?fingerprint=E4BE8D6ABFA4D9D4FEEF03CDDA7FF62A73FD64B75566F6DD4E5E577550BE8467

there is a video tutorial here: https://divestos.org/videos/tutorial-fdroid-app_repo.webm

**Comment by bushrang3r** [comment]
Oh, thank you. I wasn't being careful at all 🥺
