### ISSUE TITLE
F-Droid vulnerability warning

### ISSUE THREAD

**Issue by pirron4** [Divested-Mobile/Mull-Fenix#255]
Can someone please comment on why F-Droid is flagging Mull for vulnerability and suggesting an uninstall? 

I can't find more information about it and would like peace of mind knowing this is a non-issue.

**Comment by hardeik** [comment]
+1

**Comment by SkewedZeppelin** [comment]
Please read the news: https://divestos.org/pages/news#2024-10
> Updated Mull to [131.0.0](https://www.mozilla.org/en-US/firefox/android/131.0/releasenotes/), has 14+1+25 security fixes from the previous 129.0.2 release. In order to resolve the compilation issue introduced in 130, Mull is now compiled using Mozilla's prebuilt clang toolchain. This however is incompatible with the F-Droid.org inclusion criteria, so these updates (for now at least) will only be available via the DivestOS.org F-Droid repository. Please note, while this adds a prebuilt dependency, the result does still remain FOSS.

Use the DivestOS.org repo: https://divestos.org/pages/our_apps#repos

The F-Droid.org repository will be back on track after https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16135 merges.

**Comment by SkewedZeppelin** [comment]
The security issues the F-Droid.org version are currently vulnerable to are here:
- https://www.mozilla.org/en-US/security/advisories/mfsa2024-39/
- https://www.mozilla.org/en-US/security/advisories/mfsa2024-45/
- https://www.mozilla.org/en-US/security/advisories/mfsa2024-46/
- https://www.mozilla.org/en-US/security/advisories/mfsa2024-51/
- https://www.mozilla.org/en-US/security/advisories/mfsa2024-53/

**Comment by I-I-IT** [comment]
When switching repo however, it doesn't find a new version or it doesn't want to update.

![2618](https://github.com/user-attachments/assets/6e9ec0f8-d7e5-40f5-9b14-43971e1ded13)

**Comment by SkewedZeppelin** [comment]
@I-I-IT because they have different signatures. you unfortanetly would have to uninstall and reinstall to switch between them. or just wait a few more days for https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16135
