### ISSUE TITLE
Can't update from divestOs repository

### ISSUE THREAD

**Issue by mbbsas** [Divested-Mobile/Mull-Fenix#261]
Hi. I'm on lineageos. I've runned mull browser 129 till now. 
I want to update it. I've uninstalled it and from ffupdater tried to install it.
I get: 

Install_failed_update_incompatibile
Existing packageUs.spotco.fennec_dos  signature do noto match newer version

I can't purge the old mull version... How can I solve the problem?
Thanks

**Comment by SkewedZeppelin** [comment]
Sounds like you still have the F-Droid.org version installed, you must first uninstall it including from work or secondary user profiles too.

**Comment by mbbsas** [comment]
Sure, thnks you. 
I had another user where I still had it installed.
Thankyou
