### ISSUE TITLE
Make Developer Built .apk's Available on Github (or Gitlab or Codeberg)?

### ISSUE THREAD

**Issue by DiagonalArg** [Divested-Mobile/Mull-Fenix#264]
I wonder if the team might consider making .apk's available here on github. A number of us run GrapheneOS with [Obtainium](https://github.com/ImranR98/Obtainium). That allows us to use developer signed packages directly from github or other developer websites, which is preferable to those signed by f-droid.

**Comment by SkewedZeppelin** [comment]
[Why did you just open this after I closed ](https://gitlab.com/divested-mobile/mull-fenix/-/issues/93#note_2209408407)

**Comment by DiagonalArg** [comment]
I've seen that.  The difficulty with the direct downloads is that: 1. there's no indication of version#, so obtainium can't identify an update, and 2. that's not better than getting the f-droid signed package from their site, which is part of what we're trying to avoid.

**Comment by SkewedZeppelin** [comment]
> that's not better than getting the f-droid signed package from their site

IT IS NOT SIGNED BY F-DROID.
Those are compiled and signed by myself.

**Comment by DiagonalArg** [comment]
Ya, was just editing; but obtainium still can't work unless you have the version number on the site or in the .apk URL so it can identify an update.

**Comment by SkewedZeppelin** [comment]
I don't care about what Obtainium does or doesn't do, it is a bad idea to use it so I won't support it.

You already can use my F-Droid repo or you can direct download it, I'm not here to support a dozen other options/platforms.

**Comment by DiagonalArg** [comment]
Alright, I understand.

Just FYI, until [Accrescent](https://accrescent.app/) is out of beta, and that may be a while, the default direct-from-dev app store is obtainium.  My use of it isn't ideosyncratic.

Regardless, thank you for your work.
