### ISSUE TITLE
Install .xpi extensions directly

### ISSUE THREAD

**Issue by Guille-11** [Divested-Mobile/Mull-Fenix#267]
Mull does not allow me to install extensions from .xpi files, which limits its functionality if an extension needs to be developed and tested in mull. I suggest that this function be added, since there is no clear option to perform this installation.
It's just a suggestion

**Comment by SkewedZeppelin** [comment]
It does already.

Go to settings > about, tap Mull a bunch of times, it'll say "secret settings are enabled", and there is a custom XPI option then.
