### ISSUE TITLE
You has disabled webassembly, won't that disable new sandbox in firefox 95 (RLBox)?

### ISSUE THREAD

**Issue by rustforfuture** [Divested-Mobile/Mull-Fenix#27]
Hello

I noticed that you has disabled webassembly, won't that disable new sandbox in firefox 95 (RLBox)? 

Because seems that RLBox uses webassembly according to this article by mozilla:

https://hacks.mozilla.org/2021/12/webassembly-and-back-again-fine-grained-sandboxing-in-firefox-95/

------

Also seems that uBo uses wasm to increase its efficiency about 30 percent, doesn't disabling it, reduce the performance of uBo and increase its battery and resources usage? (Specially for mobile devices that are targeted by mull)

Thank you
Best wishes.

**Comment by SkewedZeppelin** [comment]
RLBox has nothing to do with the runtime WASM option.

**Comment by rustforfuture** [comment]
> RLBox has nothing to do with the runtime WASM option. RLBox sandboxing is enabled in Mull.

Oh, I See.
Thank you very much.

What about uBo that use wasm to make its performance better, will it get affected by that pref that is disabled?

Thank you very much.
And Thank you very much for this great app, i have eye issues and changing about:config prefa was a terrible thing for me even when my eyes haven't this much health related issues.
You really saved me :)

Best wishes.
I hope you to always stay safe and healthy.

**Comment by rustforfuture** [comment]
And Thank you very much for all your answers in other issues that i opened.

**Comment by SkewedZeppelin** [comment]
If uBlock Origin does use WASM, then it likely is impacted and will be slower.
