### ISSUE TITLE
Different search engine for private tabs

### ISSUE THREAD

**Issue by recoil1329** [Divested-Mobile/Mull-Fenix#270]
Consider adding the ability to choose one engine for normal tabs, another one for private ones. I know there is an option in the about:config which can be turned on if on pc. Vivaldi, even tho based on chromium, is a good exemple of what i mean and they have it as a feature on mobile as well so it's not imposible. As for why anyone would want this: I would like to use ecosia for general searches as it helps the inviourment in some way, but have duckduckgo or startpage as my private tab search engine. I know you can just switch them before doing a search but it isn't permenent so whenever you make a new private tab you will have to switch again and it's a lot more tedious... I hope this is something to be considered as it seems really easy to inpliment and i feel like i'm not the only one who would benefit from this :) 

Sincerly, 
An everyday Mull user

**Comment by SkewedZeppelin** [comment]
this is out of scope for a change to Mull. please try instead asking upstream for Mozilla to add such feature.
