### ISSUE TITLE
Adobe login not working on Mull

### ISSUE THREAD

**Issue by singh9596** [Divested-Mobile/Mull-Fenix#273]
Recently learned how to enable the Adguard's HTTPS filter on Mull. After enabling it, I encountered an issue where I couldn't access Facebook, adobe and many more websites. However, it was resolved by changing the value of security.cert_pinning.enforcement_level from 2 to 1, which allowed me to access the facebook. Despite this, it still failed to log in to account.adobe.com on mull (continuously reloads the enter the password screen), but works fine on fennec/firefox.

**Comment by SkewedZeppelin** [comment]
Did you perhaps try the other workarounds?
https://divestos.org/pages/broken#mull

maybe
> - Mull has stripped referrers. This often breaks loading of images on websites with hotlink protection. Navigate to about:config and change network.http.referer.XOriginPolicy from 2 to 1, this is however a privacy risk.
> - Mull has WebAssembly disabled by default. This is often used for web apps. Navigate to about:config and change javascript.options.wasm to true if needed, this is however a security risk.

**Comment by singh9596** [comment]
It took time but network.http.referer.XOriginPolicy needed the change as well. Is it not possible to whitelist a site instead of completely making global changes. (Whitelisting in adguard doesn't work).

**Comment by SkewedZeppelin** [comment]
Firefox sadly does not have per-site exceptions for these functions.

**Comment by singh9596** [comment]
Thanks
