### ISSUE TITLE
Corrupt icons on NSW public transportation website

### ISSUE THREAD

**Issue by i-am-mentally-unstable** [Divested-Mobile/Mull-Fenix#274]
This happens on the NSW government public transportation website at https://transportnsw.info/trip and a few others. I am visiting Sydney on business in a couple weeks so I would like see if I could get it working without another browser.

The map itself requires WebGL to be enabled in the config to work, but the icons and route drawings are still corrupt. The website works fine with WebGL enabled on base Firefox and Chromium. Figured it might have been a driver issue with Pixel 8, I was able to replicate it on a Pixel 3a and Galaxy S7 as well.

If there a separate disabled WebGL/js/canvas/rendering related config setting that might be causing this to occur?

Intended behavior: (Base firefox, chromium, etc)
![asintended2](https://github.com/user-attachments/assets/276f5458-472a-4f8d-93c9-cd2b02c1abe3)
![asintended](https://github.com/user-attachments/assets/a331c6ee-33d0-454a-8cb8-78c6a091114b)

In Mull:
![Screenshot_20241212-170912_Mull](https://github.com/user-attachments/assets/d745c555-015f-4d88-be59-751de27c49ee)
![Screenshot_20241212-171037_Mull](https://github.com/user-attachments/assets/68191f54-b03a-40fe-b79b-42c44fba210d)

**Comment by SkewedZeppelin** [comment]
This is likely caused by resist fingerprinting.
Please use another browser for such websites.

**Comment by i-am-mentally-unstable** [comment]
I fat fingered the enter key, my mistake. Please see updated issue and screenshots

**Comment by SkewedZeppelin** [comment]
If you add the domain to the privacy.resistFingerprinting.exemptedDomains option it should work

**Comment by i-am-mentally-unstable** [comment]
> If you add the domain to the privacy.resistFingerprinting.exemptedDomains option it should work

Thanks, that did the trick. I wonder why the toggle in the address bar doesn't seem to add them to this list if it "fully" disables anti-fingerprinting measures, but I suppose that's more of a Mozilla issue.

Thank you for your help and work on the project.
