### ISSUE TITLE
Images are not sent to server

### ISSUE THREAD

**Issue by maria-namia** [Divested-Mobile/Mull-Fenix#277]
On https://theyseeyourphotos.com/ (and other sites), when uploading a picture, the picture is not transferred to the server as can be seen by the analysis given, when uploaded. Instead a generic empty picture or something similar is received by the server ("The image shows a detailed close-up view of a textured surface. The background and foreground are indistinguishable as the texture is uniform across the entire image. The color scheme consists mainly of various shades of purple, with some thinner lines of lighter, possibly beige or pinkish hues, creating a striped pattern. There are no discernible objects or elements outside of the texture itself."). Had the same problem on other websites. On Firefox Android uploading pictures works properly

**Comment by SkewedZeppelin** [comment]
This is caused by canvas protection from resist fingerprinting.

You can either use another browser or add the domain to privacy.resistFingerprinting.exemptedDomains via about:config

**Comment by maria-namia** [comment]
> This is caused by canvas protection from resist fingerprinting.
> 
> You can either use another browser or add the domain to privacy.resistFingerprinting.exemptedDomains via about:config

Thank you!
