### ISSUE TITLE
Isn't firstparty isolation that you have enabled it, redundant with total cookie protection (aka dynamic firstparty isolation)?

### ISSUE THREAD

**Issue by rustforfuture** [Divested-Mobile/Mull-Fenix#28]
Hello

I noticed that you enabled firstparty isolation, Isn't firstparty isolation that you have enabled it, redundant with total cookie protection (aka dynamic firstparty isolation)?

Because Firefox for Android already have Total cookie protection (aka dynamic firstparty isolation) that is better for performance and in the same time seems that have same protection as firstparty isolation.

Also this is a quote from Librewolf FAQ:

> FPI is not enabled by default as we use dFPI, and the two do not work well togheter. dFPI is a newer implementation and it causes less breakage, plus it is included by default when using Tracking Protection in strict mode.

> Please also notice that dFPI makes containers and containers extensions redudant, unless you want to protect your privacy when visiting the same website multiple times, during the same browsing sessions.

> https://librewolf.net/docs/faq/#why-isnt-first-party-isolate-enabled-by-default

More links that may be good:

https://blog.mozilla.org/security/2021/06/01/total-cookie-protection-in-private-browsing/

https://www.reddit.com/r/firefox/comments/o1ntqi/privacyfirstpartyisolate_vs_total_cookie/

Thank you
Best wishes.

**Comment by SkewedZeppelin** [comment]
dFPI/TCP is not supported in Fenix.
FPI will be used until it is.
https://gitlab.com/divested-mobile/mull-fenix/-/issues/19

**Comment by sankhababu** [comment]
> dFPI/TCP is not supported in Fenix. FPI will be used until it is. https://gitlab.com/divested-mobile/mull-fenix/-/issues/19


Sir, is the situation unchanged till now?

As I've seen in the introduction part of your Browser Comparison article, you've mentioned that android Firefox, and Focus have dFPI.

Is Water Fox and Ice Raven, which are not made from scratch like Mull and Fennec f-droid, have dFPI?

Best Regards
