### ISSUE TITLE
Please also disable this if it have any advantage

### ISSUE THREAD

**Issue by 0xRustlang** [Divested-Mobile/Mull-Fenix#29]
dom.netinfo.enabled	false

Sorry, i don't know if it is useful, justs wanted to say.

I have some more, but they may cause breakages so i didn't included them :)

Best wishes.

**Comment by SkewedZeppelin** [comment]
Why?

**Comment by rustforfuture** [comment]
> Why?

Sorry, i don't remember why i disabled it.

I changed my about:config prefa may be two years ago, so i don't remember what was the reason for this.

And sorry, because of eye issues, i can search again.

Sorry, really.

**Comment by SkewedZeppelin** [comment]
No need to apologize.
