### ISSUE TITLE
Bottom toolbar options menu presentation glitch

### ISSUE THREAD

**Issue by m1chj** [Divested-Mobile/Mull-Fenix#3]
I believe that the options menu should (?) be presented like with top toolbar

https://user-images.githubusercontent.com/45080190/120811963-15d62f00-c53c-11eb-9f2b-2298bd83948c.mpmp

**Comment by SkewedZeppelin** [comment]
This would be best reported upstream.
However it seems like how it should be.
When in bottom mode it only shows partially to allow easier reaching of the higher up options.

**Comment by m1chj** [comment]
To be honest I'd never think about it since I have no problems reaching top of my screen but if it's created with small hands owners, it's actually pretty good
