### ISSUE TITLE
Sorry for question, does mull disabled google safebrowsing?

### ISSUE THREAD

**Issue by rustforfuture** [Divested-Mobile/Mull-Fenix#30]
Hello
Sorry for question, does mull disabled google safebrowsing?

If you disabled it, may you please provide info to how enable it?

Thank you very much.
Best wishes.

**Comment by SkewedZeppelin** [comment]
Safe Browsing is not disabled.
It is however set to never send off any information anywhere.
It is configured to only use the static lists and perform checks locally.
I do not recommend disabling it.
