### ISSUE TITLE
May you please share your modified version of arkenfox and tor uplift user.js that you use for mull for those that want it?

### ISSUE THREAD

**Issue by rustforfuture** [Divested-Mobile/Mull-Fenix#31]
Hello

May you please share the modified version of arkenfox user.js for those that want it?

As i have some eye related issues and one of my devices that is old doesn't support installing fennec based firefox, may you please share the modified version of arkenfox and tor uplift prefs that you change from normal firefox so me and those that are in this situation use it?

I know using old devices and old browser isn't secure but i disable JavaScript and also the user.js that you use based on my usage in other devices is very good in disabling those components that uave more potential of vulnerabilities like graphite and etc.

So if you share it, it will be great.

Also may you please share the latest release of old fennec based mull?

I searched whole F-Droid repo and its archive repo and your own repo but didn't find any 68.x version.

I have an old armv-7 device that doesn't support fenix, so i wanted to use mull or hardned version of another fennec based browser with JavaScript and such disabled in it (and with caution) for basic usages.

Thank you very much
Best wishes.

**Comment by SkewedZeppelin** [comment]
You can get older versions of Mull by adding this repo to F-Droid:
https://divestos.org/fdroid/official-archive

The list is here:
https://github.com/Divested-Mobile/Mull-Fenix/tree/master/preferences
and maintained first here:
https://github.com/divestedcg/Brace/tree/master/brace/usr/lib/firefox/browser/defaults/preferences
