### ISSUE TITLE
Accessibility force disabled by default prevents accessibility based autofill

### ISSUE THREAD

**Issue by proletarius101** [Divested-Mobile/Mull-Fenix#34]
It's seems like the privacy hardened Mull Browser has finally been supported by Bitwarden. 

Unfortunately it doesn't show me the "pop up" though. I can only use credentials using the android 11 inline auto fill (from the keyboard). Like this totp codes won't be copied unfortunately. 

This fixes the issue

`about:config -> accessibility.force_disabled 0 (mull default = 1)
`

## Relevant report
- https://www.reddit.com/r/Bitwarden/comments/p8ou0g/mull_browser_android_no_pop_up/

**Comment by SkewedZeppelin** [comment]
Yes, I had a note for this.
Thank you for confirming, I'll switch it off for next release.

**Comment by SkewedZeppelin** [comment]
This is fixed in the latest 98.1.1 release.
