### ISSUE TITLE
Reset about:config

### ISSUE THREAD

**Issue by JonnyTech** [Divested-Mobile/Mull-Fenix#35]
In order to try and get an embedded map working, I changed various settings in `about:config`.

Eventually it was `webgl.disabled = false` that fixed the issue at https://www.munzee.com/map

Is there an easy way to reset all config values to default without losing other data ie bookmarks and cookies?

**Comment by SkewedZeppelin** [comment]
On desktop there is a soft-reset option in about:support, however that is not
available on Fenix.

**Comment by JonnyTech** [comment]
OK, thanks.
