### ISSUE TITLE
Mull doesn't support security keys?

### ISSUE THREAD

**Issue by AnonWombat** [Divested-Mobile/Mull-Fenix#36]
![Screenshot_20220214-005510_Mull](https://user-images.githubusercontent.com/44946401/153808075-3aeb2e4e-ce3a-4a74-994a-c80aa794de57.png)

**Comment by SkewedZeppelin** [comment]
Google did a rude and made U2F and FIDO on Android depend on the proprietary
Google Play Services and app library.
Mull does not include this library and therefore doesn't work.

**Comment by AnonWombat** [comment]
> Google did a rude and made U2F and FIDO on Android depend on the proprietary Google Play Services and app library. Mull does not include this library and therefore doesn't work.

That's unfortunate. Man, Google sucks lmao

Anyways, thanks for the quick response!
