### ISSUE TITLE
Accept the Risk & Continue (Secure Connection Failed) button Not Working.

### ISSUE THREAD

**Issue by ghost** [Divested-Mobile/Mull-Fenix#37]

**Comment by Snub90** [comment]
@SkewedZeppelin This issue is now fixed on version 98.1.0. Thanks for fixing it !! 😃 👍

**Comment by SkewedZeppelin** [comment]
I can still reproduce this issue on 98.1.1.

**Comment by Snub90** [comment]
Oh ! thats bad :( 
But the accept risk and continue button is perfectly working on 98.1.0 version.
BTW, when i toggled "security.ssl.treat_unsafe_negotiation_as_broken" to FALSE in about:config, it took me on website rather than than 'Secure Connection Failed' Page.

**Comment by Offerel** [comment]
I have the same effect in 100.1.3. I have also installed Fennec from F-Droid in the same version where this issue didn't exist. Is it right to assume that the issue comes from some setting in about:config / arkenfox which is different from Fennec?

Would be nice to find and resolve this issue.

**Comment by SkewedZeppelin** [comment]
Here are potentailly related ones you can try

- browser.ssl_override_behavior to 1 instead of 2
- browser.xul.error_pages.expert_bad_cert to false instead of true
- network.http.referer.XOriginPolicy to 0 instead of 2
- security.OCSP.require to false instead of true
- security.ssl.require_safe_negotiation to false instead of true
- security.cert_pinning.enforcement_level to 1 instaed of 2

**Comment by Offerel** [comment]
You are my hero. After setting your first value, it worked!

**Comment by SkewedZeppelin** [comment]
This has been documented here: https://divestos.org/index.php?page=broken#mull

**Comment by Offerel** [comment]
But I have one question: Why does the page say not to disable RFP? RFP is responsible for almost 99% of the problems that at least I currently have with most websites. At least from my point of view, RFP is much too destructive to be recommended unrestrictedly and generally at the moment. I am well aware that RFP is one of the main features of Mull. Therefore, I do not want to have a fundamental discussion about it. However, I am not quite sure how Mull differs from Fennec, for example, apart from RFP. In my opinion, several other switches of Arkenfox are implemented in Mull, which are not active in Fennec. Or am I mistaken?
