### ISSUE TITLE
Additional extension support

### ISSUE THREAD

**Issue by fu8765** [Divested-Mobile/Mull-Fenix#4]
First of all. Thank you for the hard work. This is an excellent browser for someone such as myself that kept tinkering with user.JS.

Coming from iceraven, is there any way you can integrate the code that allows them to have additional extensions?

Thanks heaps

**Comment by t3dium** [comment]
This can easily just be done via custom addon collections, you can just make a firefox account on https://addons.mozilla.org/en-US/firefox/ and add desktop addons to your collection, then on mobile just click "about mull", tap the icon 3 times, then return and add your addon collection to mull.

**Comment by rustforfuture** [comment]
Also see this: https://github.com/Divested-Mobile/Mull-Fenix/issues/6#issuecomment-1003782510
