### ISSUE TITLE
Flutter web pages: html versions blurry & no scrolling, canvaskit only blank screen

### ISSUE THREAD

**Issue by thomas725** [Divested-Mobile/Mull-Fenix#40]
[Flutter](https://flutter.dev/) apps compiled to html web versions display much blurrier than in other browsers, and scrolling doesn't work.

Also tested Fennec & original Firefox Android which have no problem with scrolling and have much less blurry items.

Examples with description where scrolling should be:
- https://gallery.flutter.dev/#/ -> open the "MATERIAL" category: On other browsers you get a scroll-able list, on Mull only the first 4 items are visible.
- https://bdlukaa.github.io/fluent_ui/ -> for example if you open the "Icons" page, you get a very long scroll-able list on other browsers, on Mull: no scrolling.

When forcing the web renderer to canvaskit (default = auto which serves html version to mobile browsers) Mull displays only a blank screen. Other browsers (inculuding Firefox based ones such as Fennec) display normal, though load times are long since canvaskit require a big initial download)

**Comment by SkewedZeppelin** [comment]
Probably resistFingerprinting.
it doesn't even work on Firefox desktop with brace.

**Comment by SkewedZeppelin** [comment]
I am wrong. It actually uses WASM, which is default disabled.
Switch `javascript.options.wasm` in about:config to true

**Comment by thomas725** [comment]
I can confirm that setting "privacy.resistFingerprinting" from true (=default for Mull) to false gets both the scrolling working and the reduces the amount of blur to the same level as in other Android Firefox versions for those Flutter HTML pages. Thank you for providing this easy workaround! :)

I'm gonna retest the canvaskit version next, will update the comment here with results in the next 30 minutes.

**Comment by SkewedZeppelin** [comment]
Notably however that setting is the primary feature of Mull.
You might instead consider keeping a second browser handy like Bromite or Mulch.

**Comment by thomas725** [comment]
the canvaskit WASM version loads successfully with `javascript.options.wasm` set to true, but the performance seems much worse than other browsers. Scrolling gives me a performance of about one frame every 2 seconds, while in Fennec I don't notice any delays, feels completely smooth in Fennec (& other browsers on the same phone)

**Comment by SkewedZeppelin** [comment]
This has been added to the notes here: https://divestos.org/index.php?page=broken#mull
