### ISSUE TITLE
Embedded videos not playing

### ISSUE THREAD

**Issue by dude-shah** [Divested-Mobile/Mull-Fenix#42]
I recently downloaded Mull.
I was on a site there were multiple server mention when i clicked on them they are not loading , when i try to view online content on the browser the embedded videos are not playing. I went through all the settings but haven't found the solution. Is this a bug ... If not can someone please tell me what's the solution. 
I tried enabling all the cookies still not working. Also tried disabling enhance protection and disabled all the add-on.
I tried the same site on Iceraven and Firefox it worked.

**Comment by SkewedZeppelin** [comment]
What device and Android version?
What version of Mull?
What website?

**Comment by dude-shah** [comment]
Using 
Android 11
Realme 6
Mull latest release on github (98.1.1)
Any website .. 
I tried 9anime.to and other sites ... Clicked on anime and then choose server, the video was not loading.

**Comment by dude-shah** [comment]
I read that mull has pre hardened privacy features ..
Maybe something in **about:config** is enabled that is causing the sites to not load embedded videos. I did my research but didn't found any solution. So i thought maybe its a bug.

**Comment by SkewedZeppelin** [comment]
Those piracy sites have scripts that try to detect debuggers and adblockers.
Perhaps it is falsely tripping.

Sometimes it'd work, others not.
I don't think there is any one config to change to fix.

Just keep another browser like Mulch or Bromite or maybe Tor Browser handy.

**Comment by dude-shah** [comment]
Is there no solution to it ... I used brave with ad blocking , fingerprinting and cookies block and the site worked fine. 
On Firefox other forks, the site is working fine with ad and cookies blocked

**Comment by SkewedZeppelin** [comment]
Try this:
https://gitlab.com/divested-mobile/mull-fenix/-/issues/9#note_691876898

**Comment by dude-shah** [comment]
Thanks man .. it worked

For anyone else, who having the same problem 
Go to **about: config**
Search **network.http.referer.XOriginPolicy**
Then set is value to 0.
