### ISSUE TITLE
Web page dark theme not working

### ISSUE THREAD

**Issue by zethra** [Divested-Mobile/Mull-Fenix#43]
On devices using a dark theme, Mull should communicate that to web pages using the prefers-color-scheme css property. This works on regular Firefox for Android and Fennec. Was this intentionally removed for some reason or is this a bug?

**Comment by SkewedZeppelin** [comment]
https://gitlab.com/divested-mobile/mull-fenix/-/issues/10

**Comment by SkewedZeppelin** [comment]
https://gitlab.com/divested-mobile/mull-fenix/-/issues/10
