### ISSUE TITLE
x86 (x86_64) builds on F-Droid?

### ISSUE THREAD

**Issue by woodvale** [Divested-Mobile/Mull-Fenix#45]
Hi, since it's possible to build Mull for x86, can we get precompiled binaries on F-Droid?

**Comment by SkewedZeppelin** [comment]
It is not possible as is to compile x86

**Comment by SkewedZeppelin** [comment]
https://gitlab.com/relan/fennecbuild/-/issues/18

**Comment by woodvale** [comment]
ah, well that's a shame, thank you

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Divested-Mobile/Mull-Fenix/issues/45#issuecomment-1064811116

@SkewedZeppelin, why?
