### ISSUE TITLE
Where are the additional settings stored? 

### ISSUE THREAD

**Issue by Pillendreher** [Divested-Mobile/Mull-Fenix#5]
I have a quick question: Where is the *.js file responsible for the changes? The file "prebuild.sh" tells me that it's based on arkenfox and another js file, but I can't find said "mobile.js" anywhere, not even in the profile folder.

I'm asking because I would like to make some changes based on personal preference, but I don't want to create a mess by making the changes in "about:config".

Cheers!

**Comment by SkewedZeppelin** [comment]
mobile.js is compiled into the Gecko WebView.
If you are compiling you can just add another file to the preferences folder and cat it like so https://github.com/Divested-Mobile/Mull-Fenix/blob/master/prebuild.sh#L271

**Comment by Pillendreher** [comment]
Thanks for getting back to me! I figured as much - they're basically hardcoded as default values, right? So all I have to do in order to enforce different values is to deploy a user.js in my profile folder.

**Comment by SkewedZeppelin** [comment]
If you are rooted you should be able to copy your own user.js into:
/data/data/0/us.spotco.fennec_dos/files/mozilla/profile.default/user.js
or similar path
