### ISSUE TITLE
Firefox Sync doesn't work

### ISSUE THREAD

**Issue by catwithbanana** [Divested-Mobile/Mull-Fenix#51]
I have been using Mull + Firefox Sync (for bookmarks) for several months without issue.

Today I noticed that my account hadn't synced in nearly 24 hours. Clicking on "sync now" did nothing. I tried signing out and signing back into my account, and now the "Choose what to sync" options are greyed out. "Sync Now" still does nothing and says last synced: never.

I'm running Mull 98.2.0 on CalyxOS Pixel 5. I tried restarting the app and my phone and neither fixed the issue. When signing out and back into my account the sign in website hangs at my 2FA code, though the session shows up as signed in as expected on my account dashboard. I'm not sure if that matters or is relevant.

Do you have any ideas how I could fix this issue?

**Comment by SkewedZeppelin** [comment]
perhaps enable `identity.fxaccounts.enabled` in about:config?

**Comment by SkewedZeppelin** [comment]
Also are you using any adblocker or adblocking DNS?

**Comment by catwithbanana** [comment]
Switching identity.fxaccounts.enabled from false to true didn't change any behavior as far as I can tell.

I am running an adblocker (uBlock) and adblocking DNS but neither report blocking any Mozilla content. I can see the Firefox Accounts DNS calls resolving as expected on my DNS log. I also didn't change any configuration options for either adblocker recently, and sync was working as expected during that time.

The sync options are no longer greyed out, strangely, but the "sync now" button still doesn't do anything and is stuck at last synced: never.

I really appreciate your help. Let me know what other info I can provide to narrow things down.

**Comment by catwithbanana** [comment]
The sync just completed and the sync now button works again. Maybe it was an issue on Mozilla's end? Otherwise I have no idea what changed.

I'll close the topic for now and comment again if the problem reoccurs.
