### ISSUE TITLE
Allow showing more than 50 addons  

### ISSUE THREAD

**Issue by cleanerspam** [Divested-Mobile/Mull-Fenix#52]
Settings >About Mull>Tap on Mull 7 times  >Debug Menu enabled 

Now in Settings you can see Custom Add-On Collection   under Advanced section
Now Enter Collection Owner (User ID) = `16201230`
AND in Collection Name = `What-I-want-on-Fenix`

![IMG_20220323_165220](https://user-images.githubusercontent.com/59386233/159688707-f1dc2210-e02a-4ae5-bd81-8bc0ac03adf8.jpg)

After this Mull will close , restart Mull and and in Addon list  you can see upto 50 addons from this [List(mozilla addon store)](https://addons.mozilla.org/en-US/firefox/collections/16201230/What-I-want-on-Fenix/?page=3&collection_sort=-added)  

My problem is that Mull is not showing more than 50 addons but the list has more than 50 addons 

Please rectify this bug 
Most of the addons working 🙂
![IMG_20220323_165207](https://user-images.githubusercontent.com/59386233/159688646-618fae72-7c08-4271-8153-0b1809b3c03a.jpg)

**Comment by cleanerspam** [comment]
![gif](https://user-images.githubusercontent.com/59386233/159687908-c62a881a-8408-4a0e-969a-3c5631e2c85e.gif)

**Comment by SkewedZeppelin** [comment]
This is deliberate choice by upstream Fenix, not a bug.
I also do not recommend using any additional addons other than uBlock Origin.

**Comment by cleanerspam** [comment]
🙄
