### ISSUE TITLE
Youtube videos do not start to play (and https issue)

### ISSUE THREAD

**Issue by Offerel** [Divested-Mobile/Mull-Fenix#53]
Today, i have tried to play a Youtube video in the browser. If i click the play button, the video loads but didn't play. I don't know, if this is because of some setting from arkenfox.

Some similar thing but unrelated to youtube, is the following: I have a url not protected by https. Instead of this it is a standard http url. I can try to proceed and load the url, but click the dedicated button does nothing. Also when i open a https url with self generated certificate, i have such a button to allow opening of this url. If i click the button to allow, nothing happens. If both issues are not related to each other, please let me know, then we can create 2 separate issues, but for me it feels like the same issue.

I have tried all the above things with Fennec from F-Droid. There i have no such issues. 

If this is a arkenfox issue, it would be nice to disable optionally some of the arkenfox settings.

**Comment by SkewedZeppelin** [comment]
YouTube should work no issue.
It is one of the websites I always test before release.

The other issue where the security exception button doesn't work for self signed
certificates I am aware of, but have yet to find a fix:
https://github.com/Divested-Mobile/Mull-Fenix/issues/37

**Comment by Offerel** [comment]
I should search better before posting. I Have re-checked the video issue. Sorry, my fault, it is not the youtube page itself. This was a youtube video embedded in another page. In the meantime i have found #42 and tried the mentioned fix (network.http.referer.XOriginPolicy = 0), but at least here, it didn't work.
