### ISSUE TITLE
Site isolation is working on Firefox android nightly

### ISSUE THREAD

**Issue by rsssxd** [Divested-Mobile/Mull-Fenix#55]
https://wiki.mozilla.org/Project_Fission

https://i.postimg.cc/T1HG3Gvn/Screenshot-20220401-153740.jpg

https://i.postimg.cc/TYFf8R96/Screenshot-20220401-153900.jpg

**Comment by rsssxd** [comment]
![Screenshot_20220401-145939_Firefox_Nightly](https://user-images.githubusercontent.com/60405617/161259275-922f46d5-d364-404f-b439-b96f7a46ffe5.png)

**Comment by rsssxd** [comment]
![Screenshot_20220506-220050_Mull_1](https://user-images.githubusercontent.com/60405617/167201440-b48ec9cf-7ea1-499e-be4b-9f0d5d03175e.png)

Mull Fenix

**Comment by SkewedZeppelin** [comment]
What did you change in about:config to make about:processes have that?

**Comment by rsssxd** [comment]
gfx.webrender.all = true

fission.autostart = true

**Comment by SkewedZeppelin** [comment]
Fission will be enabled when it is ready.
