### ISSUE TITLE
Https everywhere

### ISSUE THREAD

**Issue by Landiks** [Divested-Mobile/Mull-Fenix#56]
The latest fenix update has Https Everywhere support.

Is it possible to use this feature for Mull version 99.1?

**Comment by SkewedZeppelin** [comment]
That is only in nighty so far.
It'll be in Mull when it is in Fenix stable.

**Comment by SkewedZeppelin** [comment]
This is in 100, but Mull cannot currently ship 99.x or 100.x due to a bug with extensions being non-functional.
