### ISSUE TITLE
why is Mull 99 not on Fdroid yet?

### ISSUE THREAD

**Issue by helpthemfix** [Divested-Mobile/Mull-Fenix#58]
it's been so long since Firefox 99 came out and yet Mull is not.

**Comment by SkewedZeppelin** [comment]
Mull and Fennec F-Droid are currently unable to ship 99.x due to a bug:
https://gitlab.com/relan/fennecbuild/-/merge_requests/13

**Comment by helpthemfix** [comment]
Hope it gets sorted it out. Thanks!

**Comment by realbiz21** [comment]
Is there anything we users can do to test or help?

**Comment by SkewedZeppelin** [comment]
Mull 100.1.1 is now available on the DivestOS F-Droid repo and should be on the official repo in a few days.
