### ISSUE TITLE
More add-ons

### ISSUE THREAD

**Issue by githubuser849** [Divested-Mobile/Mull-Fenix#6]
I know that in this link https://github.com/Divested-Mobile/Mull-Fenix/issues/4 developer said that uBlock Origin is available. But I would like if there would be more PRIVACY add-ons as listed in https://github.com/arkenfox/user.js/wiki/4.1-Extensions.
I use user.js in Firefox in my desktop and the add-ons I use are - 1. uBlock Origin 2. Temporary Containers 3. ClearURLs. These are the main ones which can enhance the privacy without interferring with user.js, in other words no user pref needs to be changed for these add-ons. Other useful add-ons are 4. Smart Referer-most effective when cross-origin pref is set to default state, and 5. uMatrix - its on fifth place because it is archived.
In Android before discovering Mull Browser in F-Droid yesterday, I used Iceraven and all the five add-ons are available though Temporary Containers doesn't work in Android & ClearURLs, Smart Referer and uMatrix works well. I wrote all this to give a perspective from where add-ons request is coming.

If the developer can include all three add-ons(ClearURLs, Smart Referer and uMatrix), that would be great. If all of them are not possible, then ClearURLs(or any other URL shortener in Arkenfox guide) would be the top priority for addition, as cross- origin request are covered in user.js already(though extensions allows granular precision) and to an extent uBlock Origin can make up for uMatrix absence.

Away from this, I would like to say thank you to the developer, before discovering Mull Browser(which I was aware of before, but being in F-Droid main repo is a worthy achievement), changing prefs was tiresome.

**Comment by SkewedZeppelin** [comment]
I already recommend the user install uBlock Origin.

You do not need Temporary Containers with Mull/Brace, as first party isolation is enabled.
You do not need smart referrer, that is already mitigated by XOriginPolicy.
uMatrix is too clunky to use on mobile imo, uBlock Origin with JavaScript disabled by default mode does a decent job like you mention.
ClearURLS would be nice to see.

I however have no intent to change the default addon collection.

**Comment by githubuser849** [comment]
Thank you for responding.
Yes ClearURLs is the main one. I believe with the new main ESR upgrade coming soon, hopefully that will bring more add-ons, atleast recommended by Mozilla on AMO.

**Comment by SkewedZeppelin** [comment]
You can change to the IceRaven addon collection:
- Settings
- About Mull
- Tap Mull name until it says "debug menu enabled"
- Go back
- Custom add-on collection
- Set owner to: 16201230
- Set name to: What-I-want-on-Fenix

**Comment by githubuser849** [comment]
Whoa that worked like charm. Yeah approx. 50 add-ons are available and the main one ClearURLs is available, and so problem solved.
Opening debug menu did add two more tray below account option(yes I have Firefox account signed in), Custom Mull account server and Custom Sync server and both are greyed out, non-clickable. Wondering what are those?

**Comment by githubuser849** [comment]
Both those options are for setting up custom account and server, and since I had account signed in, they were greyed out, so never mind that.

A big thanks for that add-on tip, since it worked quite well, why don't post it in homepage for other users(less technical like me) to easily find out? Just saying.

**Comment by githubuser849** [comment]
I created new add-on collection https://addons.mozilla.org/en-US/firefox/collections/16921559/Privacy-Add-ons/ 
I'm not endorsing it or anything like that but I would suggest to create a collection like this. Couple the new add-on collection with details of custom add-on collection menu would help users.

**Comment by rustforfuture** [comment]
@ghost (although i know this is unfortunately a deleted account)

You can use most of ClearURLs addon features and almost all neaturls addon features by using these filter lists:

https://cdn.jsdelivr.net/gh/DandelionSprout/adfilt@master/ClearURLs%20for%20uBo/clear_urls_uboified.txt

https://cdn.jsdelivr.net/gh/DandelionSprout/adfilt@master/LegitimateURLShortener.txt

Both will remove tracking parameters from urls (both in webpage and also in rhe website utl (urlbar).

But be aware, they can have false positives based on your browsing habits, etc.

I had no issue with then so far but if you have issues with them, you can use this discussion to report issues (both for "ClearURLs uBofied" and "Legitimate URL shorteners".

Also you can use "Adguard URL Tracking Protection" that is exist in privacy section of uBlock origin.

Although i don't know how you can report its false positives.

I know he deleted his account but i wrote this for anyone that needed this in future.


@SkewedZeppelin
And Thank you very much for great fork of Fenix, i use both (Firefox for android + mull), eatch one for specific need.
Best wishes.

**Comment by rustforfuture** [comment]
Also the reason that currently mozilla won't enable gull addon support (except the fact that they may not have ready to support them in their new codebase is this:

>     How was the previous version of Firefox for Android able to support all Firefox desktop extensions?

> ( I read this question in relation with my remark "This is one of the reasons why only a limited set of trusted extensions are supported on Android.". If not, please restate your question. )

> The previous version of Firefox for Android (Fennec) ran everything (the browser UI, web content and extensions) in a single process, so the concept of separate processes was not relevant. Modern browser architectures use multiple processes for several reasons (including reliability, performance and security), with at least a separation between privileged browser UI and third-party code (web pages). In contrast to Fennec, Firefox for Android (Fenix) now uses multiple processes for web content. As mentioned before, extensions still run in the main browser process, which is not sustainable in the long term.

Full discussion (is about webextension manifest v3):
https://github.com/w3c/webextensions/issues/51

**Comment by YukiAlmasy** [comment]
How do we add userscripts? I thought i read somewhere you can

**Comment by SkewedZeppelin** [comment]
@YukiAlmasy 

you'd need an addon for that, follow the steps above to gain access to more addons

I however only recommend the use of uBlock Origin.

**Comment by YukiAlmasy** [comment]
> @YukiAlmasy 
> 
> you'd need an addon for that, follow the steps above to gain access to more addons
> 
> I however only recommend the use of uBlock Origin.

Understood
