### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by TeaqariaWTF** [Divested-Mobile/Mull-Fenix#61]
I pinned some sites to the home page, that's fine.
but I don't want every site I visit to be added here, even though all my settings are turned off, the history continues to be added here. 

app version : 100 .1.1
There was no such error in the previous version.
![Screenshot_20220510-093144_Mull](https://user-images.githubusercontent.com/90970076/167563356-12dffbba-6d37-4140-a606-2b52cec72341.png)

![Screenshot_20220510-093528_Mull](https://user-images.githubusercontent.com/90970076/167563627-40a6bf2b-5d27-4af4-b345-777b1348b6ad.png)
When I close the shortcuts, they disappear on the sites I pinned to the screen.

**Comment by Morgan-le-Fay** [comment]
Upstream issue. Not something Mull can fix.
Read more here : https://old.reddit.com/r/firefox/comments/unz7pz/after_updating_to_build_100_i_cant_see_only_the/
