### ISSUE TITLE
fission.autostart

### ISSUE THREAD

**Issue by Log4sh3ll** [Divested-Mobile/Mull-Fenix#62]
So, I was doing some extra hardening of Mull browser where i turned on "fission.autostart"
After turning it on i started facing a lot of problems in the browser (like issue #37 , #39 & some playback issues too) but it was fixed after i turned it off.

**Comment by SkewedZeppelin** [comment]
Fission would be enabled if it worked.

**Comment by SkewedZeppelin** [comment]
Fission will be enabled when it is ready.

**Comment by SkewedZeppelin** [comment]
Fission would be enabled if it worked.
