### ISSUE TITLE
Disabling or hiding accounts or sync

### ISSUE THREAD

**Issue by ANiceReasonableKitten** [Divested-Mobile/Mull-Fenix#63]
Fenix by default pesters you to use firefox sync,  with a massive bubble in settings and an option in the three dot menu.

This is annoying for users who would rather not use sync (especially for privacy related issues)

Tor browser for example disables sync related options

**Comment by SkewedZeppelin** [comment]
Some users want Sync.

It is also the only way to backup things like bookmarks.

And Sync is end to end encrypted.
