### ISSUE TITLE
Increasing the limit of maximum custom add-ons listing

### ISSUE THREAD

**Issue by akhil247247** [Divested-Mobile/Mull-Fenix#65]
I have a custom add-ons id which consists 75 add-ons but due to Firefox maximum limit being 50 add-ons, I can't see/ install the remaining add-ons. Could you please try increase this limit to 100 or at least 75.

**Comment by SkewedZeppelin** [comment]
I do not care about addons:

https://github.com/Divested-Mobile/Mull-Fenix/issues/4
https://github.com/Divested-Mobile/Mull-Fenix/issues/6
https://github.com/Divested-Mobile/Mull-Fenix/issues/20
https://github.com/Divested-Mobile/Mull-Fenix/issues/52
https://gitlab.com/divested-mobile/mull-fenix/-/issues/31

**Comment by hockeymikey** [comment]
@SkewedZeppelin Maybe some of us do.

**Comment by nemesis256** [comment]
I have closed the issue but after reading your reply, i just want to clarify my issue. I never said that i want to install 50 addons,  i have requested you to make mull list all of the addons of a collection, cause firefox have a limit of listing only 50 addons, even if the collection have 100 addons available.
