### ISSUE TITLE
Secure Connection Failed on some sites with PowerTunnel

### ISSUE THREAD

**Issue by lepz0r** [Divested-Mobile/Mull-Fenix#69]
So I use PowerTunnel to bypass my ISP's DPI but some sites like Google, Twitter, YouTube, Facebook & GitHub doesn't work when I enable PowerTunnel but other Firefox fork like Iceraven & Firefox Nightly is working with PowerTunnel

Here's my PowerTunnel Setting:

![Screenshot_2022-06-26-18-22-39-499_io.github.krlvm.powertunnel.android.jpg](https://user-images.githubusercontent.com/7135180/175811741-edfed9ed-0185-484d-84b0-ee884d140805.jpg)

**Comment by SkewedZeppelin** [comment]
This is https://github.com/Divested-Mobile/Mull-Fenix/issues/76

Workaround here: https://github.com/Divested-Mobile/Mull-Fenix/issues/76#issuecomment-1232815479
