### ISSUE TITLE
Website Incompatibility

### ISSUE THREAD

**Issue by N8Z7JMYLU** [Divested-Mobile/Mull-Fenix#7]
[TomTom MyDrive](mydrive.tomtom.com/) cannot be used with Mull. Tested with new installations on Android 9 and 11. One or more modifications that cannot be changed by the user might be responsible.

Changing the User-agent string has no effect.

https://i.imgur.com/suCY4Ms.jpeg

**Comment by SkewedZeppelin** [comment]
In about:config set
webgl.disabled to false
webgl.enable-webgl2 to true.

**Comment by N8Z7JMYLU** [comment]
Can confirm that this fixes the issue. Thank you.
