### ISSUE TITLE
Third-party cookies bug

### ISSUE THREAD

**Issue by vin717** [Divested-Mobile/Mull-Fenix#71]
![Screenshot_20220630-033601_Mull](https://user-images.githubusercontent.com/108433267/176540098-5e933a61-e31f-4819-9f41-4c4fbe049846.jpg)

I block the 3rd party cookies in the setting but it appears there is a leak. Use DDG browser and samsung browser with disabled 3rd party block for comparison and all good over there.

**Comment by SkewedZeppelin** [comment]
can't reproduce
