### ISSUE TITLE
settings.firefox.services.mozilla.com

### ISSUE THREAD

**Issue by schoolprivacy** [Divested-Mobile/Mull-Fenix#72]
Hey
Mull keeps spamming the above url.  Is there a way to stop this phoning home?
Thanks

**Comment by SkewedZeppelin** [comment]
Mull does not disable connections to Mozilla.

Connections are required for the following:
- addon downloads/updates
- addon recovation databases
- certificate recvocation databases
- safebrowsing databases
- tracking protection blocklists
- etc.

You can see the Mozilla privacy policy here, but do note Mull does disable
unnecessary requests like telemetry, experiments, crash reports, and Push:
https://www.mozilla.org/en-US/privacy/firefox/
