### ISSUE TITLE
Frame drops when scrolling

### ISSUE THREAD

**Issue by rettetdemdativ** [Divested-Mobile/Mull-Fenix#74]
I don't know if you're aware of this issue, but Mull seems to be dropping a lot of frames in pretty much all of its animations and scrolling. At least that's what's happening on my phone. I don't experience the same problems with any of the available Firefox versions or Fennec.

Android version: 12

**Comment by SkewedZeppelin** [comment]
https://gitlab.com/divested-mobile/mull-fenix/-/issues/40

**Comment by rettetdemdativ** [comment]
Thanks for the quick reply. So this is intended and we can't expect it to be changed in the (near) future?

**Comment by SkewedZeppelin** [comment]
> we can't expect it to be changed

Indeed :(

**Comment by rettetdemdativ** [comment]
> Indeed :(

Good to know. Thanks :)
