### ISSUE TITLE
night mode and import bookmark

### ISSUE THREAD

**Issue by vjrmy** [Divested-Mobile/Mull-Fenix#75]
I want to use night mode but only in the settings and toolbar but in the website still show light mode.
How to do it?

Maybe will look like this
![Screenshot_20220711-111528_Bromite](https://user-images.githubusercontent.com/88963059/178187445-b5f10f7d-e9f6-49ea-aeea-b3161304f705.jpg)

**Comment by vjrmy** [comment]
And I want to import Bookmark `.html` file to mull browser. how to do it?

**Comment by SkewedZeppelin** [comment]
upstream issue
