### ISSUE TITLE
Secure Connection Failed with Google and Facebook while using Adguard https filtering

### ISSUE THREAD

**Issue by virusahastrabuddhe3idiots** [Divested-Mobile/Mull-Fenix#76]
The browser's 'Use third party CA certificate' from Secret settings has been turned on.
![Screenshot_20220722-002949_Mull](https://user-images.githubusercontent.com/109761000/180295772-f1948682-7ea9-440d-8452-7985e1cf33d3.png)

The browser's connection is being filtered through Adguard android app which includes HTTPS filtering.
![Screenshot_20220722-003122_AdGuard](https://user-images.githubusercontent.com/109761000/180296039-dd3f3e48-825e-496c-b679-1c06ffab2aed.png)

The browser is throwing 'Secure Connection Failed' error while searching for 'google.com', 'gmail.com', 'youtube.com' etc google websites and 'facebook.com'.
![Screenshot_20220722-002931_Mull](https://user-images.githubusercontent.com/109761000/180296658-376371c7-7a56-484b-b11f-72f8d43ac695.png)

The same is not happening with 'amazon.com', 'Pinterest.com', 'github.com' or any other regular websites.

**Comment by SkewedZeppelin** [comment]
https://divestos.org/index.php?page=broken#mull

**Comment by virusahastrabuddhe3idiots** [comment]
The google websites work when the https filtering is disabled for the browser.

![Screenshot_20220722-005429_Mull](https://user-images.githubusercontent.com/109761000/180299143-d52d5e99-b7a7-4405-8afb-7efa64096944.png)

Although, the adblocking capability of Adguard is severely hampered. Basically have to rely on Ublock Origin add-on for the same.

**Comment by virusahastrabuddhe3idiots** [comment]
The same HTTPS filtering configuration works well with Bromite browser. (After granting third party CA certificate access)

![Screenshot_20220722-011023_AdGuard](https://user-images.githubusercontent.com/109761000/180301647-45f888ef-3b50-49e9-ac45-1a66b17eb3e7.png)

![Screenshot_20220722-010928_Bromite](https://user-images.githubusercontent.com/109761000/180301676-1306b7de-5556-4ed9-b7df-d04f93e41760.png)

**Comment by SkewedZeppelin** [comment]
I can reproduce this issue.

**Comment by leacha69** [comment]
I've noticed the same problem as well. I've tested it on Mull going back to v100, same results. Oddly, Fennec F-Droid works perfectly.

**Comment by virusahastrabuddhe3idiots** [comment]
Changing the low level setting in about:config seems to solve the problem.

_security.cert_pinning.enforcement_level_

Set the value to _1_ instead of _2_.

**Comment by SkewedZeppelin** [comment]
This has been documented here: https://divestos.org/index.php?page=broken#mull

**Comment by singh9596** [comment]
> Changing the low level setting in about:config seems to solve the problem.
> 
> _security.cert_pinning.enforcement_level_
> 
> Set the value to _1_ instead of _2_.

Thanks. I was looking for the way out. It was pretty annoying vising broke websites and enabling/ diabling https filtering over n over
