### ISSUE TITLE
[FR] Ability to change app icon's colors

### ISSUE THREAD

**Issue by robotwombat** [Divested-Mobile/Mull-Fenix#77]
Hi there!

The new icon looks great, but it would be nice if we could possibly choose from a couple different color combos. The pink on green is certainly unique and colorful, but some might want a less vibrant option.

Thanks!

**Comment by SkewedZeppelin** [comment]
What would be a better palette?

**Comment by thereallinusrg** [comment]
The dark blue/purplish background Mull used with the old logo was nice, or the dark purple Firefox uses.

**Comment by thereallinusrg** [comment]
![image_purple.png](https://user-images.githubusercontent.com/59289945/194808134-c219cdd3-ca17-4d68-974a-bbce95147acd.png)

For example :)
