### ISSUE TITLE
Font issue on Pterodactyl Panel Console

### ISSUE THREAD

**Issue by invertedEcho** [Divested-Mobile/Mull-Fenix#78]
Hello,
I get this weird rendering issue on the Pterodactyl Panel Console. This issue only appears on Mull, not for example with the Fennec Browser, thats why I am opening this issue here.
See the screenshot below:
![Screenshot_20220827-013121_Mull](https://user-images.githubusercontent.com/80119822/187025072-9b64c99e-ff6c-4203-841f-df0e012ea208.png)

**Comment by invertedEcho** [comment]
Also, it does not help to disable the Enhanced Tracking Protection Mode.

**Comment by SkewedZeppelin** [comment]
That is the canvas protection from RFP.

Fenix does not offer an option to disable it per website like you can on desktop.

**Comment by invertedEcho** [comment]
Ah, I see.
Yeah, that's what I have been doing in the past. Will just continue with that.
Thanks for the quick response!
