### ISSUE TITLE
Total cookie protection (possibility)

### ISSUE THREAD

**Issue by opusforlife2** [Divested-Mobile/Mull-Fenix#79]
FF 104 has some PRs related to enabling TCP as part of an experiment. Is there any relevant code snippet in there somewhere that could be used to enable it fully for Mull users?

**Comment by SkewedZeppelin** [comment]
Mull has had FPI enabled since day 0.

**Comment by opusforlife2** [comment]
> Mull will switch to dFPI/TCP when it eventually works on Fenix.

As in you're waiting for upstream to finish ironing out all the bugs and releasing the feature in an FF version? If that's the case, no problem.

**Comment by SkewedZeppelin** [comment]
dFPI is only a refined version of FPI that improves compatibility with websites and covers a little bit more.

It currently only works on Firefox for Desktop and Firefox Focus for Android.
Fenix does not have support for it yet.

**Comment by opusforlife2** [comment]
I was going by this PR https://github.com/mozilla-mobile/fenix/pull/26449, merged 2 days ago. This adds dFPI support, right? I was mistaken about the FF 104 part, though.
