### ISSUE TITLE
Is it possible to add pull to refresh?

### ISSUE THREAD

**Issue by Sn0whax** [Divested-Mobile/Mull-Fenix#8]
Would it be possible to steal this feature from the nightly builds, or at least allow for it as an option?

**Comment by SkewedZeppelin** [comment]
I'm sure there is a flag for it that could be toggled.
But last time I tried it, it was quite buggy.
Like you'd scroll up to see the bottom bar, and end up refreshing.

**Comment by Sn0whax** [comment]
Yeah, I agree it's not perfect. 
Would be ideal for it to at least be an option. Some pages have some quirks but overall it's decent. I wonder if there's a way to at least allow for the toggle to be enabled for the end user to make the decision like on the nightly builds.

**Comment by Sn0whax** [comment]
Just wondering if there are any updates regarding this yet. Thanks for the great browser.

**Comment by SkewedZeppelin** [comment]
This will happen when Mozilla adds it to upstream Fenix.

**Comment by blogmangit** [comment]
yes please  add this feature.

**Comment by nahcos** [comment]
Ditto, please add the feature. Currently it seems to be working quite fine in the stabil Firefox.

**Comment by SkewedZeppelin** [comment]
Pull to refresh has been in Mull for two releases now.

**Comment by sconim** [comment]
> I refuse to believe it. There's no way that I missed noticing this critical feature for two months. What I think actually happened is that after this comment was posted, I was teleported to a parallel universe where this was already true.

I didn't see any announcement either, however, there are bigger problems than this. I would humbly suggest letting this one go.
