### ISSUE TITLE
Use of untrackme with mull

### ISSUE THREAD

**Issue by Ayoahha** [Divested-Mobile/Mull-Fenix#80]
Hello to the team
Have some difficulties  using mull with untrackme, in order to redirect twitter, reddit..... to their respective free equivalent websites or even YouTube to e.g. Newpipe app.

In fact, it is well working with other browsers (firefox,  vanadium in which i tested) : these browsers ask well how to open links (via untrackme or browser directly) and it is redirected correctly.

Mull does not ask this and in consequence it seems impossible to force the redirection.
Is there any solution' ? Or something linked to mull ?

Thanks for a kind reply

**Comment by SkewedZeppelin** [comment]
Have you tried enabling the "Open links in apps" option in Settings?

And there is no team.

**Comment by dri94** [comment]
You can use Scriplets for this.
Follow this guide
https://xaloez.com/blog/UblockOriginScriptlets/index.html

I have an example js file you can check out here https://gist.github.com/dri94/77718ad78da914ebc7b3b6a8c21f54b9
