### ISSUE TITLE
Site setting for images

### ISSUE THREAD

**Issue by islam2hamy** [Divested-Mobile/Mull-Fenix#81]
I want to be able to disable loading of images

Primary use case is browsing with limited bandwidth.

**Comment by SkewedZeppelin** [comment]
You can do this with uBlock Origin (which I recommend you should already have installed).

In the settings there is a size limit you can set, the default is 50KB.

**Comment by islam2hamy** [comment]
It is not working as expect , and it will not
https://github.com/gorhill/uBlock/issues/1473#issuecomment-259244428

Could you please add it as Site setting 
And showing it on the per site quick setting
Thank you

**Comment by islam2hamy** [comment]
@SkewedZeppelin

**Comment by SkewedZeppelin** [comment]
https://github.com/mozilla-mobile/fenix/issues/12711

**Comment by SkewedZeppelin** [comment]
upstream issue
