### ISSUE TITLE
Which one to install

### ISSUE THREAD

**Issue by islam2hamy** [Divested-Mobile/Mull-Fenix#82]
![IMG_٢٠٢٢٠٩٠٧_١٨٥١٥٣](https://user-images.githubusercontent.com/7989030/188935483-81350913-6e12-490f-a05f-086549a58f15.jpg)

**Comment by SkewedZeppelin** [comment]
The topmost one.

**Comment by islam2hamy** [comment]
Thier is two new release yesterday , one with 75.6 mb and other 69.2 mb
