### ISSUE TITLE
More rows of website shortcuts at homepage.

### ISSUE THREAD

**Issue by ANi1XO** [Divested-Mobile/Mull-Fenix#83]
Is it possible to have more rows of shortcuts on the homepage. Currently we have only 2 rows of shortcuts, but if we can add upto 5 rows, I believe it will be a great quality of life improvement for this app.

**Comment by SkewedZeppelin** [comment]
This is out of scope for Mull.

Search here to see if someone else has already request it as a feature for Firefox, and if not request it: https://github.com/mozilla-mobile/fenix/issues
