### ISSUE TITLE
Some websites go light mode

### ISSUE THREAD

**Issue by Imzxhir** [Divested-Mobile/Mull-Fenix#84]
I've notices that some websites like github.com have gone light mode but normally its supposed to be dark mode. This has happened on other websites as well

**Comment by SkewedZeppelin** [comment]
https://divestos.org/index.php?page=broken#mull
https://gitlab.com/divested-mobile/mull-fenix/-/issues/10
https://gitlab.com/divested-mobile/mull-fenix/-/issues/22
https://github.com/Divested-Mobile/Mull-Fenix/issues/43
https://github.com/Divested-Mobile/Mull-Fenix/issues/75#issuecomment-1180050003
