### ISSUE TITLE
Fingerprint id remains the same

### ISSUE THREAD

**Issue by ValuableEarth** [Divested-Mobile/Mull-Fenix#87]
Hey, so I have noticed recently that the fingerprinting id on Mull remains the same everytime I access fingerprint.com website. I tried with clearing all browsing data and cookies but still the id remains the same. It also shows the same id when I access the website through incognito.
I checked in about:config if privacy.resistfingerprinting is disabled but it's not.

![Screenshot_20221002-191242_Mull](https://user-images.githubusercontent.com/114863885/193458782-6311aef1-a164-4314-ba09-ff10179ce240.jpg)
![Screenshot_20221002-191249_Mull](https://user-images.githubusercontent.com/114863885/193458786-11de54aa-ac14-478a-8ce3-d08664d8aeab.jpg)
![Screenshot_20221002-191305_Mull](https://user-images.githubusercontent.com/114863885/193458787-e24081ff-4317-4527-8ea6-f8e19fbd0eb3.jpg)

I'm using Mull v105.1.0 on my Galaxy M31

**Comment by SkewedZeppelin** [comment]
Please read this: https://github.com/privacyguides/privacyguides.org/discussions/1797

**Comment by SkewedZeppelin** [comment]
Please don't use CanvasBlocker, as RFP is already enabled in Mull.
https://github.com/arkenfox/user.js/wiki/4.1-Extensions

I only recommend using uBlock Origin.

**Comment by ValuableEarth** [comment]
No, I don't use any extension other than uBlock Origin myself. Also I haven't changed any other setting in about:config. I even reinstalled Mull today and checked with all default settings. The fingerprint id changed at first but then again after clearing all data and cookies when revisiting the website the id remains same as first.

**Comment by ValuableEarth** [comment]
I installed Fennec F-droid today and set privacy.resistFingerprinting to true. In Fennec it's correctly working. The fingerprint id changes everytime I reopen the browser after clearing all cookies and data. I'm facing this issue only with Mull, don't know why.

**Comment by islam2hamy** [comment]
I have the same issue

**Comment by fosswalker** [comment]
I noticed that when webgl.disabled was set to false, the fingerprint is randomized again. I don't know why this happens, or whether enabling WebGL would lower privacy, I'm just reporting on something I noticed.

**Comment by SkewedZeppelin** [comment]
@fosswalker 
See this: https://github.com/privacyguides/privacyguides.org/discussions/1797#discussioncomment-3704584

Read this: https://github.com/privacyguides/privacyguides.org/discussions/1797#discussioncomment-3721547
