### ISSUE TITLE
Mull can't load pages after first install on 19.1

### ISSUE THREAD

**Issue by ohoes** [Divested-Mobile/Mull-Fenix#90]
Mull does not work on my Fairphone 4, pages do not load. I am using the latest version (v105.2.0), with default settings. Also tried to change some settings at about:config and to downgrade to an older version, without success. Other browsers like Fennec and Mulch do work without problems.
I have a Pixel 3a on which Mull does work fine, so problems with the network can be ruled out.

**Comment by SkewedZeppelin** [comment]
Please go to Settings > Apps > Mull > App info > Mobile data & wifi

and allow it access.

**Comment by SkewedZeppelin** [comment]
May be an issue with the shim after recent changes, still investigating.

**Comment by SkewedZeppelin** [comment]
You did not read what I wrote.

The Network permission is not the same as the data restrictions.
Please go to Settings > Apps > Mull > App info > Mobile data & wifi.

Screenshot: https://divestos.org/images/screenshots/12/Network.png

**Comment by SkewedZeppelin** [comment]
>  because shouldn't these settings already be enabled by default on first install

https://github.com/Divested-Mobile/Mull-Fenix/issues/90#issuecomment-1278226169
