### ISSUE TITLE
Status bar white issue

### ISSUE THREAD

**Issue by towfikomar** [Divested-Mobile/Mull-Fenix#93]
Statue bar become white while 
- Entering add-on page
- Entering add-on then back to setting page
- if internet connect error or site down
- i intend to search something but quit keyboard

Sry...also happening on Firefox 
![Screenshot_2022-10-29-15-59-40-07_50ecd26a21c2c56ce608de5e94733463](https://user-images.githubusercontent.com/114739840/198825576-197f4e9c-d40c-4619-a51d-50e6b6522848.jpg)
![Screenshot_2022-10-29-15-59-52-37_50ecd26a21c2c56ce608de5e94733463](https://user-images.githubusercontent.com/114739840/198825579-f1b7efec-244f-43f1-b3ad-29e8bd3ee955.jpg)
![Screenshot_2022-10-29-16-00-02-57_50ecd26a21c2c56ce608de5e94733463](https://user-images.githubusercontent.com/114739840/198825582-7e29c2ac-bef4-4e22-8e55-837a1e37a94b.jpg)
![Screenshot_2022-10-29-16-00-14-73_50ecd26a21c2c56ce608de5e94733463](https://user-images.githubusercontent.com/114739840/198825584-4fbbf11b-24de-4d55-9ba5-180d3b66e680.jpg)

**Comment by SkewedZeppelin** [comment]
if it is also happening on Firefox it is either an upstream issue or an issue with your system

**Comment by towfikomar** [comment]
Just checked on my 2nd device. 
Looks like it's a system issue of 1st device.
Sorry🥹

**Comment by towfikomar** [comment]
No white issue on Firefox beta v107 & Nightly v108
