### ISSUE TITLE
Where are the newests binaries?

### ISSUE THREAD

**Issue by PaulGrandperrin** [Divested-Mobile/Mull-Fenix#95]
It's been since September that Mull hasn't been updated on F-droid. Latest available binary is `105.1.0`.

However I see that this repo continues to be updated so I'm wondering where are the newests versions?

Thanks for your work!

**Comment by SkewedZeppelin** [comment]
The latest version is always on my repository: https://divestos.org/index.php?page=our_apps#repos

F-Droid is currently failing to compile it due to unknown reasons.

**Comment by PaulGrandperrin** [comment]
Thanks!

I added the repo to f-droid and at first, f-droid was confused and didn't understand that it could update the already installed Mull.

I uninstalled and reinstalled f-droid and now it recognize that it can update Mull!

Unfortunately, that fails...

![Screenshot_20221105-164105.png](https://user-images.githubusercontent.com/1748936/200128191-63ae3d72-8e8b-4d7e-aebd-e77d56144367.png)

I'm guessing, I might need to uninstall my previous Mull in order to install the new one from the other repository.

Can you confirm?

**Comment by SkewedZeppelin** [comment]
Yes, because F-Droid reuses package IDs but has a different signature they are incompatible. You'll have to pick one and stick with it.

To switch between them you must uninstall and then manually install from the correct source via the versions dropdown.

**Comment by PaulGrandperrin** [comment]
Ok thanks, I'll move to the updated repo and stick with it.
