### ISSUE TITLE
no custom addons in 107.1.0

### ISSUE THREAD

**Issue by zinc180** [Divested-Mobile/Mull-Fenix#96]
Did a fresh install of latest 107.1.0 enabled debugging and the option for custom addon collections doesn't show in menu anymore.

**Comment by SkewedZeppelin** [comment]
Yes, per the website https://divestos.org/index.php?page=news#XXXX-XX
> Updated Mull to 107.1.0-1, has ? security fixes. Upstream 107 appears to have removed support for custom addon collections.

https://github.com/mozilla-mobile/fenix/pull/27284

Tracking here https://gitlab.com/relan/fennecbuild/-/merge_requests/24

**Comment by SkewedZeppelin** [comment]
Fixed for next release: https://github.com/Divested-Mobile/Mull-Fenix/commit/7d2071891ceced1ae83aa4d234ff06c745d32d51

**Comment by SkewedZeppelin** [comment]
Mull 107.1.0-2 is up with this option available again.
