### ISSUE TITLE
HTML files not referenced as supported by Mull's manisfest?

### ISSUE THREAD

**Issue by Sami32** [Divested-Mobile/Mull-Fenix#98]
![IMG_20221116_013007](https://user-images.githubusercontent.com/18471069/202157763-4e10b7f2-a6d6-4912-ac62-adecfc81d63e.jpg)

As showed above Mull browser is not listed with Android 7.0 MIUI 11.

The same remark is valid for Firefox and any others forks tried.

**Comment by SkewedZeppelin** [comment]
upstream issue: https://github.com/mozilla-mobile/fenix/issues/1327

**Comment by Sami32** [comment]
+1
