### ISSUE TITLE
Feature request - Possibility to duplicate a tab

### ISSUE THREAD

**Issue by Radeon89** [Divested-Mobile/Mull-Fenix#99]
Hello,

I am in love with this App and to make it even better I would like to see introduced the possibility to duplicate a tab, simply adding an item on the menu that appears after a long press on a tab, it is something that I really love on Firefox desktop and I would like to see it implement on Mull too.

Really, thank you again for everything and keep rocking!

Cheers

**Comment by SkewedZeppelin** [comment]
https://github.com/mozilla-mobile/fenix/pull/27159
https://github.com/mozilla-mobile/fenix/issues/9956
